### ISSUE TITLE
"Create New SAM Application" doesn't work for non-node or python[2.7, 3.6] projects

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#325] opened 2019-03-01 00:41 UTC
**Describe the bug**

**To Reproduce**
* Command Palette -> Create New SAM Application
* Select anything that isn't node, python2.7, or python3.6

**Expected behavior**
* Don't pop up an error message. no-op seems reasonable

**Screenshots**
![image](https://user-images.githubusercontent.com/742829/53608429-99dc2800-3b77-11e9-834c-be07555ee0de.png)

**Comment by mpiroc** [comment] 2019-04-19 21:40
Closing as duplicate of #322

**Closed by mpiroc** 2019-04-19 21:40 UTC
Labels: category:bug
