### ISSUE TITLE
amazonq: telemetry notice text shows "Null Extension Description"

### ISSUE THREAD

**Issue by tverney** [aws/aws-toolkit-vscode#5541] opened 2024-09-04 14:13 UTC
## Problem

<img width="472" alt="Screenshot 2024-09-04 at 10 07 24 AM" src="https://github.com/user-attachments/assets/0bf1b72d-6784-4809-8d95-9d4eb921172f">

Is  "Null Extension Description" expected?

## Steps to reproduce the issue

1. Meet the conditions !isCloud9() && !hasUserSeenTelemetryNotice()
2. See the message

## Expected behaviour

Have a proper description in the notification.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Darwin arm64 23.6.0
-   Visual Studio Code version: 1.92.2
-   AWS Toolkit version: v3.22.0
-   Amazon Q version: v1.23.0

**Comment by jpinkney-aws** [comment] 2024-09-04 14:24
Are you seeing this when developing or in the production vsix?

If its when developing, It's expected right now because of how the project is setup. See: https://github.com/aws/aws-toolkit-vscode/issues/4658

**Comment by tverney** [comment] 2024-09-04 14:28
It was on the production VSIX, when I've loaded the installed version in my IDE. Isn't all the times, so might have an edge case to be captured.

**Comment by justinmk3** [comment] 2024-11-08 22:05
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/4658

**Closed by justinmk3** 2024-11-08 22:05 UTC
Labels: bug
