### ISSUE TITLE
Credentials profile invalid

### ISSUE THREAD

**Issue by jdurnil2** [aws/aws-toolkit-vscode#817] opened 2019-11-18 17:16 UTC
**Describe the bug**

When trying to connect get a credentials profile invalid immediately. credentials have been changed to all lowercase, aws toolkit has been uninstalled and installed again
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version:
-   AWS Toolkit for Visual Studio Code Version:

**Additional context**

**Comment by awschristou** [comment] 2019-11-19 17:39
Hi @jdurnil2 thanks for reaching out. Are you able to verify that your credentials are valid (for example, if you have the AWS CLI installed, are you able to run `aws s3 ls` to list your S3 buckets using the same credentials)

Can you please share what your profile's keys are (do not share the actual values)

**Comment by jdurnil2** [comment] 2019-11-19 18:19
Christopher thanks for the quick reply. I am behind a proxy that doesn’t seem to like to verify ssl certificates. I verified that once I set the environment variables http_proxy and https_proxy and also put in --no-verify-ssl in the aws command I can connect. So I assume that this is the problem I am facing with asw toolkit.

Thank you,
Jason Durnil

**Comment by awschristou** [comment] 2019-11-19 18:42
Nice, thank you for trying that out. Currently the toolkit does not have proxy support. This is being tracked in https://github.com/aws/aws-toolkit-vscode/issues/185 (#185) .

**Comment by bhupesh-sf** [comment] 2019-11-25 13:08
I am facing the same issue and I am able to run `aws s3 ls` from cli. But when I hit connect to aws from vs code it immediately throw error saying:

>Unable to write to User Settings because aws.profile is not a registered configuration.

Still struggling, tried everything.

**Comment by bhupesh-sf** [comment] 2019-11-25 13:10
Also facing the issue with detecting SAM CLI, following is the error:

> Unable to write to User Settings because aws.samcli.location is not a registered configuration.

**Comment by bryceitoc9** [comment] 2019-11-25 16:38
Hi @bhupesh-sf , are you also behind a proxy? If so, we currently don't have support, as @awschristou said. I'm not 100% sure that your issue is related, though, this sounds like a VS Code extension issue. Are you able to access any of the AWS extension's functionality? Could you try uninstalling and re-installing the configuration?

If you can access some AWS extension functionality and you're not behind a proxy, could you please open another issue to track your problems?

**Comment by awschristou** [comment] 2019-12-17 01:31
Closing this issue as a duplicate of #185

**Closed by awschristou** 2019-12-17 01:31 UTC
Labels: bug
