### ISSUE TITLE
Error enumerating ECS services in AWS Toolkit for VSCode when more than 10 services running

### ISSUE THREAD

**Issue by danwit-at-lytx** [aws/aws-toolkit-vscode#2404] opened 2022-01-07 01:36 UTC
**Describe the bug**

Can't view ECS services in AWS Toolkit for Visual Studio Code when more than 10 services exist in a cluster

**To Reproduce**
1. Create a cluster in AWS with more than 10 services. 
2. Install AWS Toolkit Extension for VS Code (I'm using running VS Code on a Mac)
3. From VS Code navigate to the AWS extension, select ECS in the Explorer, browse to the cluster you created
4. Get error "Failed to load resources (click for logs)". 
5. Error in log is "InvalidParameterException: service names can have at most 10 items."

**Expected behavior**
See the list of services

**Desktop (please complete the following information):**

-   OS: Darwin x64 20.6.0
-   Visual Studio Code Version: 1.63.2
-   AWS Toolkit Version: 1.34.0

BTW unrelated to the original bug but the About AWS Toolkit dialog is missing a newline character between the "Visual Studio Code Extension Host Version: X" line and the "AWS Toolkit Version: Y" line.

**Comment by JadenSimon** [comment] 2022-01-07 17:57
Duplicate of #2362

> BTW unrelated to the original bug but the About AWS Toolkit dialog is missing a newline character between the "Visual Studio Code Extension Host Version: X" line and the "AWS Toolkit Version: Y" line.

Nice find!

**Comment by justinmk3** [comment] 2022-01-13 22:50
Toolkit 1.35 includes a fix for this issue. Thank you for reporting it!

**Closed by justinmk3** 2022-01-13 22:50 UTC
Labels: bug, duplicate, pending-release
