### ISSUE TITLE
CodeCatalyst dev environment sessions timing out

### ISSUE THREAD

**Issue by sahilrc** [aws/aws-toolkit-vscode#4758] opened 2024-04-20 04:00 UTC
## Problem

With timeout in CodeCatalyst dev environments set to 15 minutes, I'm kicked out of the SSH session after 15 minutes of use, while still having VSCode active on my machine. 

## Steps to reproduce the issue

1. Connect to a CodeCatalyst dev environment with timeout set
2. Wait till specified timeout
3. VSCode states: "Reconnecting to SSH: aws-devenv"

## Expected behavior

Not kicked out.

I was able to workaround this by specifying "No timeout" in the CodeCatalyst console.

## System details 

-   OS: Mac Sonoma 14.3.1
-   Visual Studio Code version: 1.87.2
-   AWS Toolkit version: v2.20.0

**Comment by mrpackethead** [comment] 2024-04-20 07:44
Its 'SSH session' rather than RDP, session. 

I'm getting the same thing.  THe development system will shut down after its timeout period irrispective of activity or not. 

THis issue only started mid this week.  IT was working just fine.



Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

AWS Toolkit v2.20.0

**Comment by boomclickthump** [comment] 2024-04-25 00:02
I can confirm that reverting to 2.18.0 resovles the issue as well.

**Comment by mrpackethead** [comment] 2024-04-25 00:37
Looks like aws are making a fix

https://github.com/aws/aws-toolkit-vscode/pull/4811

**Comment by justinmk3** [comment] 2024-04-30 08:05
Fixed in the latest AWS Toolkit.

**Closed** 2024-04-30 08:05 UTC
Labels: bug, pending-release, remote-execute, service:codecatalyst

**Comment by mrpackethead** [comment] 2024-04-30 20:12
@justinmk3 , I've installed and will try it out and come back to you and let you know after using it for a day.
