### ISSUE TITLE
SAM debug will error if template is not "template.yaml"

### ISSUE THREAD

**Issue by hayleyday** [aws/aws-toolkit-vscode#1546] opened 2021-03-09 15:04 UTC
**Describe the bug**

When running a aws-sam debug configuration, the template file name must be "template.yaml" or AWS Toolkit will throw an error: `Invalid (or missing) template file (path must be workspace-relative, or absolute): c:\Users\me\my-workspace\myproject\myprojectfolder\template-test.yaml`

**To Reproduce**

1. Have a SAM application working with a debug configuration
2. Change template file name to anything else other than "template.yaml"
3. Change templatePath in launch.json to match the new file name
4. Attempt to run your debug configuration and see AWS Toolkit error

**Expected behavior**

Template file can be named anything and debug session runs successfully.

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Visual Studio Code Version: 1.54.1
-   AWS Toolkit Version: 1.20.0

**Additional context**

My vscode debug configuration that will throw the error:

>         {
>             "name": "mydebugname",
>             "type": "aws-sam",
>             "request": "direct-invoke",
>             "invokeTarget": {
>                 "target": "template",
>                 "templatePath": "myprojectfolder/template-test.yaml",
>                 "logicalId": "MyProjectFunction"
>             },
>             "lambda": {
>                 "payload": {
>                     "path": "events/event.json"
>                 }
>             },
>             "sam": {
>                 "containerBuild": true,
>                 "dockerNetwork": "myproject_default"
>             }
>         }

Note: I have my template in a folder, but the same issue will happen if the template is in the root of the project.
Another note: SAM is happy to run with other template file names - such as "template-test.yaml"

**Comment by justinmk3** [comment] 2021-03-09 16:42
Might be an issue with the "template registry". It only scans for "template.yaml" files: https://github.com/aws/aws-toolkit-vscode/blob/b3b9e4e444f54e034d2bd92ea0150bc5f3a83f43/src/shared/cloudformation/activation.ts#L15

Proposal:

- Whenever a caller requests an "invalid" path from the template registry, the registry should double-check the filesystem and update its beliefs

**Comment by ParkerSch** [comment] 2021-06-10 23:37
This is absolutely maddening.  Anyone figure out a workaround here or have an update?

**Comment by bryceitoc9** [comment] 2021-06-10 23:51
We're looking to add some additional YAML handling, which will probably expand to extending the file watcher to all `.yaml` and `.yml` files, with a heuristic to determine whether or not they're Cloudformation/SAM. The heuristic is first going to be used to apply autocompletion to template files: https://github.com/aws/aws-toolkit-vscode/pull/1748

**Comment by justinmk3** [comment] 2022-12-15 00:32
Test steps:

1. renamed template.yaml to template-test.yaml
2. restarted vscode
3. AWS Toolkit recognizes `template-test.yaml` as a SAM file and enables language features (via json-schema)
4. setting `"templatePath": "${workspaceFolder}/lambda-nodejs18.x/template-test.yaml"` in the `launch.json` config 
5. ✅  F5 debugging on the launch config was able to run and hit a breakpoint
    - fixed by https://github.com/aws/aws-toolkit-vscode/commit/ed8f69c4f5509a4ce53822cb676a16020ba76d58
6. ❌ viewing the `template-test.yaml` file does not show the `AWS: Add Debug Config` codelenses.
    - caused by: https://github.com/aws/aws-toolkit-vscode/blob/a2b40951639db71d07e83ecf0fa5bf5c6497fd6f/src/shared/sam/activation.ts#L198

**Closed by justinmk3** 2022-12-15 00:32 UTC
Labels: bug, sam

**Comment by paul-uz** [comment] 2024-07-22 14:03
@justinmk3 not sure where you got that info, but v3.15.0 still has this issue

**Comment by paul-uz** [comment] 2024-07-22 14:47
> @paul-uz need more details. Please open a new issue describing the exact steps that reproduce your issue

Turns out you need to enable an option in the code lens settings
