### ISSUE TITLE
command 'aws.login' not found

### ISSUE THREAD

**Issue by Kareem871** [aws/aws-toolkit-vscode#2331] opened 2021-11-23 12:22 UTC
**Describe the bug**

After installing AWS toolkit  in VScode when ever trying to make any transaction it returns Command 'aws.<Command>' not found.

**To Reproduce**

1. Install AWS toolkit from vscode extensions.
2. Ctrl+Shift+P, choose AWS: <Any command>
3. See error

**Screenshots**

When trying to connect to AWS:

![image](https://user-images.githubusercontent.com/62218150/143022096-775fd387-0437-4b3c-aff6-a3172f691d87.png)

When trying to create credentials:

![image](https://user-images.githubusercontent.com/62218150/143022214-884b21ff-a15b-4d1d-abcf-852c47e2aa09.png)

**Desktop (please complete the following information):**

-   OS: Windows 10 NT X64
-   Visual Studio Code Version: 1.63.3
-   AWS Toolkit Version: 1.34.0 

**Additional context**

I tried older version of AWS toolkit: 1.28 and it worked just fine.

**Comment by bryceitoc9** [comment] 2021-11-23 16:26
Hi @Kareem871 ,

* Is any other AWS functionality working in the toolkit? (e.g. can you create a SAM application)
* Is there any output related to the extension in the AWS Toolkit Logs or Log (Extension Host) output channels?

**Comment by Kareem871** [comment] 2021-11-23 19:02
Hi @bryceitoc9,

- I tried many other functionalities and all returned the same.
- I checked the logs, I reinstalled many times, it produces this log over and over:

      2021-11-23 13:58:31 [ERROR]: log level: info
      2021-11-23 13:58:31 [INFO]: Retrieving AWS endpoint data
      2021-11-23 13:58:31 [INFO]: OS:  Windows_NT x64 10.0.Version
      2021-11-23 13:58:31 [INFO]: Visual Studio Code Extension Host Version:  1.62.3AWS Toolkit Version:  1.34.0
      2021-11-23 13:58:31 [INFO]: telemetry cache not found: 'c:\Users\Kareem\AppData\Roaming\Code\User\globalStorage\amazonwebservices.aws-toolkit-vscode\telemetryCache'
      2021-11-23 13:58:31 [ERROR]: Error Activating AWS Toolkit: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again. 
      Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.
          at w.toConfigurationEditingError (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1925:18903)
          at w.doWriteConfiguration (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1925:15725)
      2021-11-23 14:03:32 [INFO]: telemetry: sent batch (size=1)

**Comment by JadenSimon** [comment] 2021-11-24 00:14
Looks like an uncaught error on start-up preventing commands from being registered. Do your user settings contain any errors? You can view them by running the command: `Preferences: Open Settings (JSON)`.

Of course, the toolkit should be catching this error regardless. Working on a fix.

**Comment by justinmk3** [comment] 2021-11-24 18:42
could be same root cause as https://github.com/aws/aws-toolkit-vscode/issues/2225#issuecomment-949993141

**Comment by Kareem871** [comment] 2021-11-26 17:39
![image](https://user-images.githubusercontent.com/62218150/143615944-a2dc4fc1-4af4-40e2-af23-ba5e56f2216d.png)

There is two problems in Preferences: Open Settings (JSON), I am not sure what is the root cause.

**Comment by justinmk3** [comment] 2022-01-13 22:54
AWS Toolkit 1.35 includes a potential fix for this, please let us know if there is still an issue after updating.

**Closed by justinmk3** 2022-01-13 22:54 UTC
Labels: bug, pending-release

**Comment by SmartManoj** [comment] 2022-09-03 06:19
Have two versions in `~\.vscode\extensions`. Deleted them and reinstall works.
