### ISSUE TITLE
The credentials do not appear to be valid, when trying to setup new credential

### ISSUE THREAD

**Issue by zeta1178** [aws/aws-toolkit-vscode#703] opened 2019-07-20 05:49 UTC
**Describe the bug**

The credentials do not appear to be valid (self signed certificate in certificate chain). Would you like to try again?

2019-07-20 01:45:27 [ERROR]: Error: self signed certificate in certificate chain
	at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
	at TLSSocket.emit (events.js:182:13)
	at TLSSocket.EventEmitter.emit (domain.js:442:20)
	at TLSSocket._finishInit (_tls_wrap.js:631:8)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 x64
 - Visual Studio Code Version: 1.36.1
 - AWS Toolkit for Visual Studio Code Version: 1.36.1

**Additional context**

**Comment by kiiadi** [comment] 2019-07-22 15:59
At what point in the workflow are you seeing this issue? Are you trying to create a new project? Access the AWS explorer? Deploy an application? Invoke a remote AWS Lambda?

**Comment by zeta1178** [comment] 2019-07-24 16:43
I see the issue when trying to access the AWS Explorer within the VS Code Application

**Comment by bryceitoc9** [comment] 2019-07-29 21:16
Are you currently running the extension through a proxy? If so, we haven't directly implemented support in the toolkit; we're tracking the issue here: https://github.com/aws/aws-toolkit-vscode/issues/618

**Comment by justinmk3** [comment] 2020-02-25 23:11
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/185

See also https://github.com/aws/aws-toolkit-vscode/issues/899

**Closed by justinmk3** 2020-02-25 23:11 UTC
Labels: needs-response

**Comment by AbhilashPurohith** [comment] 2021-06-25 06:23
Go to Visual Studio -> Settings icon -> Settings -> search for Proxy -> Remove http proxy if any -> uncheck Http: Proxy Strict SSL -> restart Visual studio code    

This solved my problem. 

If at all you are not able to do it. Try removing proxy from settings.. Go out of VPN and then try it again. 

Or else check if u are setting any http proxy in your environmental variables. Remove it and try
