### ISSUE TITLE
"Scanning CloudFormation templates..." notification never goes away/finishes

### ISSUE THREAD

**Issue by ConnorChristie** [aws/aws-toolkit-vscode#3510] opened 2023-05-30 14:25 UTC
## Steps to reproduce the issue

1. Install AWS Toolkit
2. Open a large workspace with lots of files and folders.
3. Observe that on any file open, you see this "Scanning CloudFormation templates..." notification.
4. Close the notification.
5. Open a new file.
6. And the notification re-appears with the same loading bar and never finishes.

## Expected behavior

My assumption is that the file scan is just never completing because there are so many files and if so, perhaps you could utilize the user's search exclude list to ignore irrelevant files.

Or give me an option to fully disable this feature and prevent CFN template discovery / watching.

## System details (run the `AWS: About Toolkit` command)

-   OS: Linux x64 5.4.242-162.348.amzn2int.x86_64
-   Visual Studio Code version: 1.78.2
-   AWS Toolkit version: 1.74.0

**Comment by justinmk3** [comment] 2023-06-01 19:46
> Or give me an option to fully disable this feature and prevent CFN template discovery / watching.

Disabling the `aws.samcli.enableCodeLenses` should [help with that](https://github.com/aws/aws-toolkit-vscode/pull/3445) , but it doesn't fully disable this feature.

We are working on more total performance improvements: https://github.com/aws/aws-toolkit-vscode/issues/3216

**Comment by ConnorChristie** [comment] 2023-06-05 21:55
> > Or give me an option to fully disable this feature and prevent CFN template discovery / watching.
> 
> Disabling the `aws.samcli.enableCodeLenses` should [help with that](https://github.com/aws/aws-toolkit-vscode/pull/3445) , but it doesn't fully disable this feature.
> 
> We are working on more total performance improvements: #3216

Thank you but it seems that option was already disabled for me. Tried toggling it and that did not make a difference.

**Comment by GPhilo** [comment] 2023-06-26 09:48
Adding to this, it seems that whenever the scan is in progress, all other extensions stop working. This is making it impossible for me to continue using the extension, as even with `aws.samcli.enableCodeLenses` set to false, the scan keeps getting triggered and blocks my workspace for several minutes every time I open it.

**Comment by justinmk3** [comment] 2023-06-26 14:34
> whenever the scan is in progress, all other extensions stop working. ... even with `aws.samcli.enableCodeLenses` set to false

@GPhilo can you try vscode's `extensions.experimental.affinity` setting? https://github.com/aws/aws-toolkit-vscode/issues/2703#issuecomment-1202215085 :

1. Run the vscode command `Preferences: Open User Settings (JSON)`
2. Add or update the `"extensions.experimental.affinity"` setting:
   ```
   "extensions.experimental.affinity": {
       "amazonwebservices.aws-toolkit-vscode": 1
   },
   ```

**Comment by GPhilo** [comment] 2023-06-26 15:44
I'll enable the setting and give it an in-depth try tomorrow, from a first look it seems that it improves the situation greatly already.

**Comment by GPhilo** [comment] 2023-07-03 09:48
So, after a few days with the affinity setting enabled, I still notice very big delays in other extensions while the "Scanning CloudFormation templates..." task is running.
Is there a way to disable CloudFormation linting altogether? I do not use CloudFormation templates at all and my workspace is very big, which I suspect is the reason why the scanning for templates takes forever to complete.

**Comment by justinmk3** [comment] 2023-07-03 16:54
> Is there a way to disable CloudFormation linting altogether?

Not yet, but performance is one of our priorities in the near/medium-term.

**Comment by justinmk3** [comment] 2023-08-24 21:46
> perhaps you could utilize the user's search exclude list to ignore irrelevant files.

Implemented in AWS Toolkit 1.86. Specifically, all directories mentioned by `files.exclude`, `search.exclude`, and `files.watcherExclude` vscode settings are ignored by the AWS Toolkit "Scanning CloudFormation templates" feature.

That provides a flexible workaround, but the root cause of the performance issue could still be improved, so leaving this issue open.

**Comment by GPhilo** [comment] 2023-08-25 14:01
I think it would at least be good to add one non-standard-vscode setting to that list, so that one could use that setting to exclude parts of hiw workspace, while not affecting other VSCode functionalities.

**Comment by lonmiller** [comment] 2023-09-03 13:53
> > perhaps you could utilize the user's search exclude list to ignore irrelevant files.
> 
> Implemented in AWS Toolkit 1.86. All directories mentioned by the standard vscode settings `files.exclude`, `search.exclude`, and `files.watcherExclude`, are ignored by the "Scanning CloudFormation templates" feature.
> 
> That provides a flexible workaround, but the root cause of the performance issue could still be improved, so leaving this issue open.

This is not helpful. The CloudFormation scan hangs vscode at startup. I don't want the scan at all, but I want search to work for my other extensions and find in files.

**Comment by justinmk3** [comment] 2023-09-04 12:04
The next step in improving this behavior is to make it "just in time" so that it doesn't try to scan until SAM features are actually needed. Supporting "exclude patterns" was a low-risk way to ameliorate some (but not all) scenarios.

**Comment by emrainey** [comment] 2023-09-06 15:13
The correct approach is to allow users _who do not have CloudFormations_ to *disable it*.  Not exclude locations. ZERO scanning.

**Comment by ayush987goyal** [comment] 2023-10-17 05:27
@justinmk3 Do we have a timeline on when (or if) this setting (to disable scans) be released?

**Comment by bryceitoc9** [comment] 2023-10-20 21:03
Hey all,

I'm taking a look into this right now...my suspicion isn't necessarily the file watcher's performance, but the fact that we're essentially loading every since YAML file in the workspace. Out of curiosity, do the repos that you're having problems with have a lot of `.yaml`/`.yml` files?

**Comment by ayush987goyal** [comment] 2023-10-21 01:48
@bryceitoc9 Thanks for taking a look into it. In my case, there is not a single .yaml/.yml files in my workspace. I appreciate us looking into it from the performance standpoint as we should but can we just skip this and have a separate setting to disable it altogether?

We can continue looking into the performance issues for the people interested in these scans in parallel but having the setting will immediately benefits a lot of the users right now.

**Comment by justinmk3** [comment] 2023-10-23 09:48
Adding a setting to disable this is non-trivial because SAM features depend on it. The work needed to make a "disable" setting work is similar to the work needed for the scan to be "on-demand". 

Meanwhile you can disable this by setting `files.watcherExclude`.

**Comment by GPhilo** [comment] 2023-10-23 09:52
Unfortunately, disabling via `files.watcherExclude` does not only affect the AWS Toolkit functionality and is an unacceptable workaround, as we do rely on other functionality using file watchers.

**Comment by justinmk3** [comment] 2023-10-23 10:05
Understood. This issue is still open and we're continuing to work on it.

**Comment by bryceitoc9** [comment] 2023-10-23 16:26
I'm not 100% sure what the sequencing is, but I've also merged https://github.com/aws/aws-toolkit-vscode/pull/3931 , which was rescanning the workspace multiple times for each runtime we support...I'm not sure if VS Code attempts to run this scanner at the same time as the YAML one (where the message is generated from).

If you want to give this a crack before the next release, you can try the VSIX built from this change: go to https://d1ihu6zq92vp9p.cloudfront.net/f528c2c1-b1d5-4585-b105-a639c4f9f439/report.html and download the primary artifact on that page.

**Comment by justinmk3** [comment] 2023-10-26 21:18
In AWS Toolkit 1.96, the "Scanning CloudFormation templates..." should no longer show except when using a SAM feature of AWS Toolkit. 

Currently it will still trigger if you open a SAM `template.yaml` file, even if the `aws.samcli.enableCodeLenses` is set to false. We are looking at changing that behavior.

**Closed by justinmk3** 2023-10-26 21:18 UTC
Labels: bug, pending-release, service:cloudformation, performance

**Comment by justinmk3** [comment] 2023-12-14 22:30
> Currently it will still trigger if you open a SAM `template.yaml` file, even if the `aws.samcli.enableCodeLenses` is set to false.

In the next release of AWS Toolkit (2.3.0), `aws.samcli.enableCodeLenses` also controls whether codelenses are enabled in `template.yaml` files.
