### ISSUE TITLE
The AWS Feedback and Help sub menus were showing across all the extension

### ISSUE THREAD

**Issue by msivasubramaniaan** [aws/aws-toolkit-vscode#4111] opened 2023-12-01 16:00 UTC
## Problem

The Feedback and Help sub menus are added to every Extension installed in VSCode. These options should only be displayed only for the AWS extension and the condition needs to be checked in package.json while displaying.
Looking at the codebase, I am assuming [this](https://github.com/aws/aws-toolkit-vscode/blob/de87a40d2df73f1b9e7dd64a9b3251f0e699bc55/package.json#L1409) line might have caused the issue.

**Comment by justinmk3** [comment] 2023-12-01 16:16
Confirmed, looks like our `when` clause is too loose: https://github.com/aws/aws-toolkit-vscode/blob/de87a40d2df73f1b9e7dd64a9b3251f0e699bc55/package.json#L1410

We plan to release a fix early next week.

**Comment by msivasubramaniaan** [comment] 2023-12-01 16:17
Related to https://github.com/redhat-developer/vscode-openshift-tools/issues/3653

**Comment by mohitsuman** [comment] 2023-12-01 16:17
Thanks for the quick update @justinmk3

**Comment by justinmk3** [comment] 2023-12-01 18:16
@msivasubramaniaan @mohitsuman can you confirm the fix in this vsix: https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease

**Comment by msivasubramaniaan** [comment] 2023-12-02 04:18
@justinmk3 the mentioned pre-release is working as expected. Thanks for the quick response and hope we are getting the main release by next week.

**Comment by justinmk3** [comment] 2023-12-11 21:46
2.2.0 was released with this fix https://github.com/aws/aws-toolkit-vscode/blob/master/CHANGELOG.md#220-2023-12-06

**Closed by justinmk3** 2023-12-11 21:46 UTC
Labels: bug, pending-release
