### ISSUE TITLE
Getting the codebase of existing lambda functions and iterate over them..

### ISSUE THREAD

**Issue by ibmkaga** [aws/aws-toolkit-vscode#392] opened 2019-03-21 20:16 UTC
**Is your feature request related to a problem? Please describe.**
For all the lambda functions that have been deployed on AWS, by myself or some other team member, it would help that instead of just listing those functions in the AWS view in VSCode, we could get them locally make changes and push back. I believe CLoud9 provides that integration and it will be lovely to have something similar in VSCode also. 

**Describe the solution you'd like**
Docuble clicking or a context menu option to get the function come down to the local SAM environment.

**Describe alternatives you've considered**
None other than manually doing it right now which is a pain. 

My alias @kgambhi

**Comment by awschristou** [comment] 2019-03-25 01:19
Thank you for the request @ibmkaga - out of curiosity, what language(s) are you working with in your Lambda functions?

There is some overlap between this and #105

**Comment by ibmkaga** [comment] 2019-03-25 13:00
Largely using nodeJS and python.

**Comment by mpiroc** [comment] 2019-04-19 21:43
Closing as a duplicate of #105.

**Closed by mpiroc** 2019-04-19 21:43 UTC
Labels: category:feature-request, needs-design, needs-discussion
