### ISSUE TITLE
It make Vscode slower.

### ISSUE THREAD

**Issue by imostafizur** [aws/aws-toolkit-vscode#3222] opened 2023-03-10 06:25 UTC
Type: <b>Bug</b>

After installing this extension, VSCODE goes slower. It is activation:1137ms.

Extension version: 1.64.0
VS Code version: Code - Insiders 1.77.0-insider (502ac5b213e373026527efdbcea4e669d930d9e1, 2023-03-09T05:22:23.670Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.13GB free)|
|Process Argv|--crash-reporter-id 11d3cf1c-db82-407b-8aa0-9f2982f112b3|
|Screen Reader|no|
|VM|22%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30659907
pythonb192:30661256
funwalk2:30682974
pythonms35:30671666
a2ce3375:30680469
57b77579:30677314

```

</details>

**Comment by justinmk3** [comment] 2023-03-13 15:38
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/1918 

Startup performance is something we definitely want to address this year.

**Closed by justinmk3** 2023-03-13 15:38 UTC
Labels: performance
