### ISSUE TITLE
Authentication fails if .aws/credentials doesn't exist

### ISSUE THREAD

**Issue by pcolmer** [aws/aws-toolkit-vscode#1292] opened 2020-09-11 11:34 UTC
**Describe the bug**

Attempting to connect (authenticate) the extension to AWS fails if $HOME/.aws/credentials doesn't exist.

**To Reproduce**

1. Make sure that $HOME/.aws exists, and contains a valid config file but no credentials file.
2. Try to connect to AWS in the extension.
3. Pick a valid profile from the list offered.
4. The process stops at this point with an error.

**Expected behavior**

Assuming that the selected profile is valid and works, I would expect the connect process to continue. Indeed, creating an empty "credentials" file within the ".aws" directory solves the problem.

**Desktop (please complete the following information):**

-   OS: Windows_NT x64 10.0.19041
-   Visual Studio Code Version: 1.49.0-insider
-   AWS Toolkit Version: 1.13.0

**Additional context**

```
2020-09-11 12:26:32 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:VSProdAdmin. Toolkit will now disconnect from AWS. [Error: ENOENT: no such file or directory, open 'C:\Users\phili\.aws\credentials'
	at Object.openSync (fs.js:440:3)
	at Object.func [as openSync] (electron/js2c/asar.js:140:31)
	at Object.readFileSync (fs.js:342:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
	at Object.readFileSync (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:109095)
	at constructor.o [as parseFile] (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1195321)
	at constructor.loadFrom (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1195750)
	at Object.getProfilesFromSharedConfig (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:122336)
	at constructor.load (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1198030)
	at constructor.coalesceRefresh (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1191295)
	at constructor.refresh (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1199243)
	at constructor.get (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1191121)
	at e (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1192345)
	at constructor.resolve (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1192389)
	at c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:120550
	at new Promise (<anonymous>)
	at constructor.resolvePromise (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:120487)
	at f.<anonymous> (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:784602)
	at Generator.next (<anonymous>)
	at c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:783145
	at new Promise (<anonymous>)
	at n (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:782890)
	at f.getCredentials (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:784297)
	at t.CredentialsStore.<anonymous> (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1305610)
	at Generator.next (<anonymous>)
	at c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1304870
	at new Promise (<anonymous>)
	at n (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1304615)
	at t.CredentialsStore.setCredentials (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1305547)
	at t.CredentialsStore.<anonymous> (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1305426)
	at Generator.next (<anonymous>)
	at o (c:\Users\phili\.vscode-insiders\extensions\amazonwebservices.aws-toolkit-vscode-1.13.0\dist\extension.js:2:1304672)] {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\phili\\.aws\\credentials'
}
```

**Comment by awschristou** [comment] 2020-09-11 15:40
Closing as a duplicate of #641 - please add a reaction on that issue so that we can track impact.

**Closed by awschristou** 2020-09-11 15:40 UTC
Labels: auth, bug, duplicate
