### ISSUE TITLE
The extension keeps changing User's Snippet Suggestions setting

### ISSUE THREAD

**Issue by pc-lover** [aws/aws-toolkit-vscode#2732] opened 2022-06-30 07:21 UTC
## Problem
The extension keeps changing user's Snippet Suggestions setting

## Steps to reproduce the issue
1. Install the extension2. 
2. Search for `Editor: Snippet Suggestions` on user's settings page
3. The setting value is changed to `top` and will be set to `top` again every time vscode reloads.

## Expected behavior
The extension doesn't modify `Editor: Snippet Suggestions` on user's settings page

## System details
-   OS: macOS 12.4
-   Visual Studio Code version: 1.68.1
-   AWS Toolkit version: 1.43.0

![image](https://user-images.githubusercontent.com/19520603/176617468-0bd36b3d-9c8e-402b-800b-fbf56a3b22f9.png)

**Comment by fangwade007** [comment] 2022-06-30 14:14
Caused by this line: https://github.com/aws/aws-toolkit-vscode/blob/master/src/codewhisperer/activation.ts#L466

**Comment by justinmk3** [comment] 2022-07-01 00:02
AWS Toolkit 1.44 includes a fix for this. Thank you for reporting this!

**Closed by justinmk3** 2022-07-01 00:02 UTC
Labels: bug, pending-release, codewhisperer
