### ISSUE TITLE
MFA serial in credentials is being ignored

### ISSUE THREAD

**Issue by odbaeu** [aws/aws-toolkit-vscode#1624] opened 2021-04-07 10:14 UTC
When I define mfa_serial in the source_profile or in the credentials file, AWS Toolkit would not ask me for a MFA token which causes an "access denied" error.

Here is a config that works because I defined mfa_serial directly in the profile:
~/.aws/config:
```
[default]
region = eu-central-1

[profile foo]
role_arn = arn:aws:iam::***:role/AdminRole
mfa_serial = arn:aws:iam::***:mfa/foo
source_profile = default
```

~/.aws/credentials:
```
[default]
aws_access_key_id = asdf
aws_secret_access_key = asdf
```

Here is a config that does not work because I defined mfa_serial in the source_profile:
~/.aws/config:
```
[default]
region = eu-central-1
mfa_serial = arn:aws:iam::***:mfa/foo

[profile foo]
role_arn = arn:aws:iam::***:role/AdminRole
source_profile = default
```

~/.aws/credentials:
```
[default]
aws_access_key_id = asdf
aws_secret_access_key = asdf
```

Here is a config that does not work because I defined mfa_serial in the credentials file:
~/.aws/config:
```
[default]
region = eu-central-1

[profile foo]
role_arn = arn:aws:iam::***:role/AdminRole
source_profile = default
```

~/.aws/credentials:
```
[default]
aws_access_key_id = asdf
aws_secret_access_key = asdf
role_arn = arn:aws:iam::***:role/AdminRole
```

**Comment by bryceitoc9** [comment] 2021-04-19 21:47
Thinking this may be a consequence of using the JS SDK `sharedIniFileCredentials`; this appears to require the `mfa_serial` in the profile definition itself in order to trigger the `tokenCodeFn`: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html . I think we'd either have to parse through the credential chain manually in order to get the `mfa_serial`, or we might be able to get away with using a ChainableTemporaryCredential: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ChainableTemporaryCredentials.html

Longer-term, I think the v3 SDK does a better job of parsing through the chain: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_ini.html ; specifically, see https://github.com/aws/aws-sdk-js-v3/blob/7135cd6266101c9dfc4893f4fe18b5d85e2dbd8c/packages/credential-provider-ini/src/index.ts#L220

**Comment by odbaeu** [comment] 2021-06-01 10:58
Hi @JadenSimon,

thank you for solving this so fast, I'm very surprised! It's beed a busy time but now I had the time to test your fix.
All described scenarios work with your change!

Thank you very much!!

**Comment by justinmk3** [comment] 2021-06-01 13:49
We have not yet merged the fix, so would like to keep this open.

**Comment by justinmk3** [comment] 2021-08-19 23:29
Fixed in AWS Toolkit 1.29

**Closed by justinmk3** 2021-08-19 23:29 UTC
Labels: bug, auth, pending-release, fixed-in-sdk-v3

**Comment by akulbe** [comment] 2022-09-09 18:35
This still doesn't work for me. I'm guessing when I'd try to connect to an MFA-required account, it should pop up a window asking me for the token?

If that's how it's *supposed* to work, it's still not working. I have a the latest version of the extension, as well... (and it's several versions past the beta listed here.

I normally run Insiders, but I set up a new VM and tried to see if it'd work with the stable version. I still hit the same issue.

**Comment by JadenSimon** [comment] 2022-09-09 23:29
Hey @akulbe 

Is `mfa_serial` present in the credentials profile you're selecting or is it located in the source profile? It's possible that an edge case was missed. A simple example to reproduce this issue would be extremely helpful.

**Comment by akulbe** [comment] 2022-09-10 03:06
It was like this:

[ks]
aws_access_key_id = my_access_key_id_ks
aws_secret_access_key = my_secret_access_key_id_ks
mfa_serial = arn:aws:iam::<our account number>:mfa/aaron.kulbe


[akulbe]
aws_access_key_id = my_key_id
aws_secret_access_key = my_secret_access_key_id


[default]
aws_access_key_id = my_access_key_id_ks
aws_secret_access_key = my_secret_access_key_id_ks
mfa_serial = arn:aws:iam::<our account number>:mfa/aaron.kulbe

Then I tried with only the [default] block, and removed the other two. 

Neither permutation worked.

**Comment by akulbe** [comment] 2022-09-10 03:08
I had our account number on the mfa_serial line, too, but it didn't come across in the copy/paste. In doing this from my phone, atm

**Comment by JadenSimon** [comment] 2022-09-12 16:12
@akulbe

Looks like you're not being prompted for an MFA token because none of those profiles use `role_arn`. Here's some [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-mfa) on how to set that up.

Once you have a valid role you can use, you should be able to add a profile that looks something like this:
```ini
[profile role-with-mfa]
role_arn= arn:aws:iam::our_account_number:role/MyRole
mfa_serial = arn:aws:iam::our_account_number:mfa/aaron.kulbe
source_profile = akulbe
```

Then you can use `role-with-mfa` to login with the Toolkit.

**Comment by akulbe** [comment] 2022-09-13 18:26
What if you're not *in* a role?

**Comment by akulbe** [comment] 2022-09-13 18:27
@JadenSimon What if you're not *in* a role?

**Comment by JadenSimon** [comment] 2022-09-13 19:02
> What if you're not in a role?

At the moment this just isn't supported by the Toolkit, but it seems like it could be supported. I'm tracking this feature request here: https://github.com/aws/aws-toolkit-vscode/issues/2885
