### ISSUE TITLE
CodeLens handler spawns many rg processes, slows down the machine

### ISSUE THREAD

**Issue by efreibe** [aws/aws-toolkit-vscode#1248] opened 2020-08-17 22:20 UTC
**Describe the bug**

After activating the extension it's impossible to work in macos, a bunch of rg processes slows down my computer considerably. 

After a minute or two those processes ends and  the mac become usable again, but then I start to type a line in vscode 
and happens again. It makes impossible to work.

If I uninstall the extension and restart, all it is place again.

**To Reproduce**

1. Go to Extensions
2. Install the AWS extension
3. Open a vscode project (javascript in my case)
4. Start to typing, do some code completion processes, write a few lines.
5. Go to activity monitor, there are a bunch of rg processes eating all available CPU.

**Expected behavior**

To work normally inside vscode editor.

**Screenshots**

![image](https://user-images.githubusercontent.com/1061126/90448370-9f0a9b00-e0bb-11ea-9cc8-2eb48e9e93de.png)

**Desktop (please complete the following information):**

OS:  Darwin x64 19.6.0
Visual Studio Code Version:  1.48.0
AWS Toolkit Version:  1.12.0

**Additional context**

VS CODE
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by justinmk3** [comment] 2020-08-17 22:44
Interesting, thanks for the report. Toolkit does not explicitly start rg, but rg is shipped with VSCode and may be used indirectly for some "glob" searches. I wonder, is the project you're working on very big?

> processes ends and the mac become usable again, but then I start to type a line in vscode
and happens again.

That's definitely odd, I can't immediately think of any filesystem operations we would do in response to editing text.

Seeing the arguments to `rg` may be a very useful clue. While the issue occurs, can you run this command and post the result (after scrubbing any private filepaths, if necessary):

```
ps aux | grep '\brg\b'
```

**Comment by efreibe** [comment] 2020-08-18 18:01
These are my results, I haven't found anything relevant to the case, but I suspect that maybe the cause is that the project is located in a samba shared folder (could be something related to the network not as fast as local HDD)

The fact is, if I disable the extension, there are no 'rg' processes launched and everything works normally.

`mount`

```
//macos@192.168.0.77/sos-contador on /System/Volumes/Data/sos-contador (smbfs, nodev, nosuid, automounted, noowners, noatime, nobrowse, mounted by macos)
```

`ps aux | grep '\brg\b'`
```
macos  18392  18.4  0.0  4357944   4084   ??  U     2:43PM   0:05.05 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18359  18.1  0.0  4358012   4308   ??  U     2:43PM   0:07.06 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18354  17.9  0.0  4358012   4320   ??  U     2:43PM   0:07.92 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18353  17.4  0.0  4358012   4280   ??  U     2:43PM   0:07.60 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18385  16.6  0.0  4358012   4184   ??  U     2:43PM   0:05.70 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18342  15.9  0.0  4358012   4304   ??  U     2:43PM   0:10.27 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18364  15.8  0.0  4357944   4264   ??  R     2:43PM   0:07.47 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18369  15.6  0.0  4358012   4220   ??  U     2:43PM   0:05.70 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18348  15.3  0.0  4358012   4324   ??  U     2:43PM   0:08.97 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18343  14.3  0.0  4358012   4380   ??  U     2:43PM   0:07.77 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18370  14.1  0.0  4358012   4212   ??  U     2:43PM   0:06.34 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18377  14.0  0.0  4357944   4112   ??  U     2:43PM   0:04.83 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18337  13.5  0.0  4358012   4240   ??  U     2:43PM   0:11.01 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18387  13.1  0.0  4358012   4256   ??  U     2:43PM   0:05.16 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18379  12.6  0.0  4358012   4280   ??  U     2:43PM   0:04.70 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18372  12.0  0.0  4358012   4268   ??  U     2:43PM   0:05.24 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18391  11.6  0.0  4358012   4240   ??  U     2:43PM   0:04.11 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18380  11.5  0.0  4357944   4208   ??  U     2:43PM   0:04.45 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18373  11.4  0.0  4358012   4156   ??  U     2:43PM   0:05.69 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
macos  18384  11.4  0.0  4358012   4160   ??  R     2:43PM   0:04.99 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --no-config --no-ignore-global
```

`code --status`
```
Version:          Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS Version:       Darwin x64 19.6.0
CPUs:             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)
Memory (System):  16.00GB (0.61GB free)
Load (avg):       15, 11, 7
VM:               25%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       82   17694  code main
    0       49   17709     gpu-process
    0       16   17711     utility
    4      246   17712     window (cobro.js — sos-contador)
    0      164   18111       extensionHost
    0       16   18240         electron_node aslServer.js 
    0       16   18241         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=18111
    0       49   18257         electron_node tsserver.js 
   34      606   18258         electron_node tsserver.js 
    0       49   18260           electron_node typingsInstaller.js typesMap.js 
    0       16   18112       watcherService
    0       66   18117       searchService
   13        0   19603         electron_node package.js 
   15        0   19606         electron_node package.js 
   10        0   19607         electron_node package.js 
   15        0   19608         electron_node package.js 
   16        0   19609         electron_node package.js 
   14        0   19610         electron_node package.js 
   15        0   19611         electron_node package.js 
   15        0   19612         electron_node package.js 
   15        0   19613         electron_node package.js 
   14        0   19614         electron_node package.js 
   13        0   19615         electron_node package.js 
   16        0   19616         electron_node package.js 
   15        0   19617         electron_node package.js 
   14        0   19618         electron_node package.js 
   15        0   19619         electron_node package.js 
   14        0   19620         electron_node package.js 
   12        0   19621         electron_node package.js 
   15        0   19622         electron_node package.js 
   16        0   19623         electron_node package.js 
   14        0   19624         electron_node package.js 
   13        0   19625         electron_node package.js 
   14        0   19626         electron_node package.js 
   12        0   19627         electron_node package.js 
   14        0   19628         electron_node package.js 
    0        0   18891       /bin/zsh -l
    0        0   19629         bash /usr/local/bin/code --status
    1       33   19639           electron_node cli.js 
    0        0   19198       /bin/zsh -l
    0       82   18108     shared-process
    0        0   19646       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (cobro.js — sos-contador)
|    Folder (sos-contador): 3566 files
|      File types: cs(1451) js(384) asp(332) bcmap(168) png(122)
|                  properties(105) css(92) txt(72) json(51) jpg(45)
|      Conf files: package.json(19) csproj(9) sln(7) settings.json(1)
```

Take into account that the `ps` command and `code` command were executed in separate tests so pids won't match.

**Comment by justinmk3** [comment] 2020-08-18 19:04
Great info! Probably caused by: https://github.com/aws/aws-toolkit-vscode/blob/6d7215a575ef5cd8d8746a20a7af80b32a940198/src/shared/codelens/typescriptCodeLensProvider.ts#L14

> maybe the cause is that the project is located in a samba shared folder (could be something related to the network not as fast as local HDD)

Yes. Even so, we should try to be less noisy with the CodeLens handler, especially for filesystem operations...

**Comment by hunterwerlla** [comment] 2020-11-20 22:06
@efreibe thanks for this bug report! The next release of the toolkit should use significantly less system resources for CodeLenses

**Comment by justinmk3** [comment] 2020-12-02 00:32
Toolkit 1.16 was released today and includes a fix for this issue.

**Closed by justinmk3** 2020-12-02 00:32 UTC
Labels: Hacktoberfest, bug, pending-release, performance
