### ISSUE TITLE
webviews (Lambda "Invoke", StepFunctions "Start Execution", ...) lose state after switching to another tab

### ISSUE THREAD

**Issue by oscaretu** [aws/aws-toolkit-vscode#1257] opened 2020-08-20 16:28 UTC
**Describe the bug**

If I have a tab with  a file in VSCode and I open AWS Toolkit to invoke a remote lambda, a new tab appears, where I can choose a file, or paste the JSON for the event. I invoke the lambda, and wait until the logs appear. If I click in another tab (for an open file), and then I go back to the tab where I invoked the lambda, all the information (event JSON) has disappeared.

**To Reproduce**

1. Open any file in VSCode.
2. Open AWS Toolkit to invoke a remote lambda: a new tab appears.
3. Paste the JSON for the event.
4. Press the "invoke" button to execute the lambda
5. Wait until the execution end (you can see it in the logs).
6. Click in the tab for the open file.
7. Click in the tab where you invoked the lambda.
8. You can see that all the information has disappeared (in the textarea for JSON event).

**Expected behavior**

The  information in the textarea for the event JSON shouldn't disappear, so I can make minor changes to the JSON to invoke again invoke the lamda again with the modified data.

**Desktop (please complete the following information):**

-   OS: `Windows 10 Home x64 10.0.18363`
-   Visual Studio Code Version: OS: 
   ```
   Version: 1.48.0 (system setup)
   Commit: db40434f562994116e5b21c24015a2e40b2504e6
   Date: 2020-08-13T07:50:42.600Z
   Electron: 7.3.2
   Chrome: 78.0.3904.130
   Node.js: 12.8.1
   V8: 7.8.279.23-electron.0
   OS: Windows_NT x64 10.0.18363
   ```
-   AWS Toolkit Version: v1.12.0

**Comment by justinmk3** [comment] 2020-08-20 17:28
Confirmed. Thanks for reporting! Related code: https://github.com/aws/aws-toolkit-vscode/blob/e691811d87f00050450f4973181578961e5e9467/src/lambda/commands/invokeLambda.ts#L99

**Comment by bryceitoc9** [comment] 2020-08-20 18:39
The "proper" way to do this is with get/setState: https://code.visualstudio.com/api/extension-guides/webview#getstate-and-setstate , although this does have a couple weird edge cases (e.g. if you click into the tab and away before the content is able to load). We can also retainContextWhileHidden: https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden , but this is generally reserved for more complex scenarios.

**Comment by beck3905** [comment] 2020-11-09 16:04
I just submitted https://github.com/aws/aws-toolkit-vscode/issues/1389 which is now closed as a duplicate of this.  This is not just an issue with the "Lambda Invoke" window, it is also an issue with the Step Function "Start Execution" window.

**Comment by justinmk3** [comment] 2020-12-02 00:32
Toolkit 1.16 was released today and includes a fix for this issue.

**Closed by justinmk3** 2020-12-02 00:32 UTC
Labels: Hacktoberfest, bug, good-1st-issue, pending-release, service:lambda
