### ISSUE TITLE
Investigate proxy support.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#618] opened 2019-06-14 22:32 UTC
Answer the following questions:

* What work is required to enable proxies for each runtime?
* What is our test plan for proxy support? I.e. should we replicate a proxy environment using Fiddler4?

**Comment by awschristou** [comment] 2019-11-19 18:37
Closing this as a duplicate of #185

**Closed by awschristou** 2019-11-19 18:37 UTC
Labels: feature-request
