### ISSUE TITLE
Users can specify region when deploying Sam apps so they can control the deployment destination

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#315] opened 2019-02-27 18:18 UTC
Currently, deploying a Sam application uses the first region in the AWS Explorer. This isn't obvious, particularly when multiple regions are in the Explorer.

Also, when deploying to an S3 bucket that is not in the target region, the error message is not obvious.

Acceptance criteria:
* Sam publish experience includes a prompt to select which region they would like to deploy to
* prompt defaults to the first region in the Explorer (simple implementation first, we can design for an improved experience separately)
* s3 bucket is validated prior to deployment, to ensure it is associated with selected region

**Comment by bryceitoc9** [comment] 2019-03-05 22:29
A few thoughts:
* Do we read the `~/.aws/configure` file? If so, I would prefer to default to the default region there.
* Should we list available S3 buckets in the region? Should we allow users to create a bucket in this flow?
* Wasn't sure if bucket region was taken into account for SAM deployments--can confirm that it is.

**Comment by awschristou** [comment] 2019-03-05 22:38
* The Explorer contains the regions that the user has set up, which generally contain the default region (we will likely change the behavior to auto-add default instead of the current prompt). I don't think Pickers have a default, so the spec is a little misguided there. Perhaps, the regions in the selector could be decorated with text indicating which ones are showing in the Explorer?
* We should list S3 buckets, but that can be a future task. There are more details to spec out, such as create vs already-exist, and querying for which region the bucket is associated with, and how we might cache that data to improve performance. The current title could be adjusted to mention that the bucket must already exist, and be associated with their chosen region.

**Comment by bryceitoc9** [comment] 2019-03-05 23:51
@awschristou Confirmed through local testing that our current SAM deploy wizard does use the region stored in `~/.aws/config` (since this `sam` function is just an AWS CLI wrapper). We'll have to take whatever selected region we use and pass it through with the `--region` parameter to override.

I'm not 100% sure I'm a fan of using the first region in the list as default as it might not be the most clear why it's the top of the list, and there's no easy way to reorder that list. Maybe instead just bump the whole list up to the top?

**Comment by awschristou** [comment] 2019-03-05 23:58
We should explicitly pass region into SAM CLI.
Let's start simple, by showing the full region set in the selector, with no order adjustments.

**Comment by bryceitoc9** [comment] 2019-03-07 19:39
First crack at a PR, still requires some cleanup but is functional: https://github.com/aws/aws-toolkit-vscode/pull/342

**Comment by bryceitoc9** [comment] 2019-03-11 18:29
PR updated.

* Sam publish experience includes a prompt to select which region they would like to deploy to
  * ✔️ 
* prompt defaults to the first region in the Explorer (simple implementation first, we can design for an improved experience separately)
  * Currently prompting all regions.
* s3 bucket is validated prior to deployment, to ensure it is associated with selected region
  * Should this still be in-scope for this issue?

**Comment by bryceitoc9** [comment] 2019-03-11 19:08
Created https://github.com/aws/aws-toolkit-vscode/issues/354 to cover the S3 bucket issue. Considering this out of scope for this issue.

**Closed** 2019-03-12 18:11 UTC
Labels: feature-request
