### ISSUE TITLE
support EC2, ECS metadata endpoints

### ISSUE THREAD

**Issue by sthulb** [aws/aws-toolkit-vscode#918] opened 2020-02-01 23:20 UTC
It would be great if the VSCode extension understood both the EC2 & ECS metadata endpoint configurations

**Describe the solution you'd like**
The extension should be able to understand and find the credentials from the EC2 metadata endpoint and the ECS metadata endpoints

**Additional context**
This would be useful for Workspace users and internal Amazon/AWS tooling (ping for further info thulsimo@)

**Comment by justinmk3** [comment] 2020-07-30 21:39
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/1007

**Closed by justinmk3** 2020-07-30 21:39 UTC
Labels: auth, feature-request
