### ISSUE TITLE
No code suggestion, please fix

### ISSUE THREAD

**Issue by navein97** [aws/aws-toolkit-vscode#5318] opened 2024-07-15 01:28 UTC
## Problem
No code suggestion, please fix

## Steps to reproduce the issue
Install Amazon Q extension on vscode
type code
no suggestion

## Expected behavior
no suggestion

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows
-   Visual Studio Code version: 1.91.1
-   AWS Toolkit version: the said workforce or IAM credentials, so i dont think i have any right, but i installed v3.14.0
-   Amazon Q version: 1.14.0

**Comment by justinmk3** [comment] 2024-07-15 14:22
What exact steps did you take when signing in? Please describe the steps exactly.

Can you provide the Amazon Q logs? 

1. In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run `Amazon Q: View Logs`. This reveals the Output panel with `Amazon Q Logs` selected.
2. Click the gear icon and choose `Debug`, then click it again and choose `Set As Default`.
3. Perform the steps to reproduce the issue.
4. Remove any private info from the logs.

**Comment by navein97** [comment] 2024-07-15 14:32
![image](https://github.com/user-attachments/assets/b9532e7f-38fe-4720-92c0-a681779f6e11)

**Comment by navein97** [comment] 2024-07-15 14:35
![image](https://github.com/user-attachments/assets/47edbf84-217f-4019-bba4-98d0dafe6517)
Here is also another example

**Comment by leigaol** [comment] 2024-07-16 17:35
Can you provide the logs? Meanwhile, it seems like you opened a vue file, vue is not one of our supported programming language. See https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-language-ide-support.html

**Comment by justinmk3** [comment] 2024-07-16 17:43
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/3097

**Closed by justinmk3** 2024-07-16 17:43 UTC
Labels: bug, auth-credentials, needs-response, codewhisperer, amazonq
