### ISSUE TITLE
Don't clear input JSON in the Start Execution window

### ISSUE THREAD

**Issue by beck3905** [aws/aws-toolkit-vscode#1389] opened 2020-11-07 21:38 UTC
**Describe the bug**

I'm not sure if this is a feature request or a bug...

When I right click on a Step Function in the Explorer window and choose "Start Execution" the Start Execution window appears.  When I add my execution input either as JSON or from a file everything works well.  However, if I navigate in VSCode to a different tab or window, when I return to the Start Execution window my input is gone and I have to re-enter it.  I would expect that my input would remain in the window until I clear it myself, update it, or close the window.

**To Reproduce**

1. Go to AWS:Explorer pane
2. Expand "Step Functions"
3. Right click on a step function resource and click on "Start Execution"
4. When the "Start Execution" window appears, enter some input into the text box
5. Navigate to a different tab in VSCode
6. Navigate back to the "Start Execution" tab where you just entered text in the text box
7. Notice that the text box is empty

**Expected behavior**

The text in the text box should still be in the text box when I return to the window.

**Desktop (please complete the following information):**

OS:  Darwin x64 19.6.0
Visual Studio Code Version:  1.50.1
AWS Toolkit Version:  1.15.0

**Comment by justinmk3** [comment] 2020-11-08 15:21
Thanks for the report. This is a duplicate of https://github.com/aws/aws-toolkit-vscode/issues/1257

**Closed by justinmk3** 2020-11-08 15:21 UTC
Labels: bug
