### ISSUE TITLE
Debugger not working invalid (or missing) template file

### ISSUE THREAD

**Issue by daaru00** [aws/aws-toolkit-vscode#1395] opened 2020-11-13 08:33 UTC
**Describe the bug**

Lambda debug does not works, when press to "Start Debugging" button an error appear:
```
Invalid (or missing) template file (path must be workspace-relative, or absolute):
```

**To Reproduce**

1. Open template.yaml
2. Press on button "Add Debug Configuration"
3. Configure Lambda payload and environmentVariables (optional)
4. Press on "Start Debugging"

The `.vscode/launch.json` file look like this:
```
{
  "configurations": [
    {
      "type": "aws-sam",
      "request": "direct-invoke",
      "name": "MyFunction",
      "invokeTarget": {
        "target": "template",
        "templatePath": "template.yaml",
        "logicalId": "MyFunction"
      },
      "lambda": {
        "runtime": "nodejs12.x",
        "payload": {
          "path": "event.json"
        },
        "environmentVariables": {
          "MY_VARIABLE": "test"
        }
      }
    }
  ]
}

```

**Expected behavior**

The Lambda function start locally and VSCode debug is attached to it

**Desktop (please complete the following information):**

-   OS: Linux
-   Visual Studio Code Version: 1.51.1
-   AWS Toolkit Version: v1.15.0

**Additional context**

The template file path is correct position, I tested with a simple "stat/file/cat" in terminal and the path is correct, same behaviour using relative or absolute path.
```bash
$ file template.yaml
template.yaml: ASCII text
```
```bash
$ file /home/me/project/template.yaml # just an example or my absolute path
template.yaml: ASCII text
```

The template file is correct, I currently deploy it as SAM application without any issue.

**Comment by justinmk3** [comment] 2020-11-13 15:38
If you edit and save the template.yaml file, then try again, does it work? This might be a bug in the "template registry".

**Comment by bryceitoc9** [comment] 2020-11-13 15:59
Alternately, does restarting the IDE work? If not, how did you create the launch config; did you generate it from a codelens in the template file/was it generated automatically upon creating a SAM application? Additionally, do you have more than one top-level folder in your workspace (the pathing should be relative to a top-level folder in the workspace).

**Comment by daaru00** [comment] 2020-11-13 16:20
Hi all,

thanks for the quick reply! I tried both suggested workaround:

1. remove .vscode/launch.json

2. click on button "Add Debug Configuration"

here the generated file without changes:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "aws-sam",
      "request": "direct-invoke",
      "name": "sam-eventbridge-enricher:EnricherFunction",
      "invokeTarget": {
        "target": "template",
        "templatePath": "template.yaml",
        "logicalId": "EnricherFunction"
      },
      "lambda": {
        "payload": {},
        "environmentVariables": {}
      }
    }
  ]
}
```
3. executed the debug and I receive the error

@justinmk3 I don't know if understand well your suggestions, I assumed there was some hook on saving the file.

4. saved the `template.yaml` file adding comments, saving file again..
5. executed again the debug and I receive the error

@bryceitoc9 tried your suggestion but seems did not resolve

6. restarted the IDE 
7. executed again the debug and I receive the same error

Could be something related to my template.yml that cannot parsed correctly? I try a guess, does it support this syntax?
```yml
RoleArn: !GetAtt PutEventRole.Arn
```
```yml
Resource: 
   - !Join ['', ['arn:aws:s3:::', !Ref ImageBucket, '/*']]
```

**Comment by justinmk3** [comment] 2020-11-13 17:06
Can you confirm that  you have `/home/me/project/` open in vscode as a workspace? The Toolkit resolves relative paths against the current workspace.

**Comment by daaru00** [comment] 2020-11-13 17:24
> Can you confirm that you have /home/me/project/ open in vscode as a workspace? The Toolkit resolves relative paths against the current workspace.

Yes, tried many time providing absolute and relative path and checking in VSCode terminal console (that start in current working directory) reading file with `cat`, checking with `stat`, `file` and the template file is there. Also in the error message the path is resolved absolutly and it is correct (checked with "right click" -> "copy text").

My VSCode workspace has nothing special, just opened the project folder from "open folder" command.

> Can you share a screenshot of your VSCode File Explorer tree?

![file-explore](https://user-images.githubusercontent.com/8782994/99101578-137ea880-25dd-11eb-8d97-d2f48b43851a.png)

**Comment by justinmk3** [comment] 2020-11-13 19:04
There were some improvements/changes to template handling that have not been released yet.  Could you try this prerelease build? 

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/5538833/buildArtifacts.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by daaru00** [comment] 2020-11-13 20:24
Installed the version you linked and I correctly see the new version number:

![version](https://user-images.githubusercontent.com/8782994/99117310-c78c2d80-25f5-11eb-9b30-81f6ba48818d.png)

unfortunately did not solve the problem, same error doing the same tests as before (VSCode restart and file saving included)

**Comment by bigdaddyrus** [comment] 2020-11-15 01:25
+1

**Comment by justinmk3** [comment] 2020-11-16 16:37
@daaru00 does adding `projectRoot` to the launch config also fix the issue for you?

**Comment by daaru00** [comment] 2020-11-16 20:51
VSCode print some lint-like error when I try to add a `projectRoot` property using target "template":
![config-issue](https://user-images.githubusercontent.com/8782994/99303901-ed157300-2851-11eb-80af-f5e72d5e4e67.png)
maybe is just ignored, same error..

@bigdaddyrus using target "code" it works perfectly! just need to add Lambda's runtime because, I suppose, is no more evaluated from `template.yml`. Here my configuration:
```json
    {
      "type": "aws-sam",
      "request": "direct-invoke",
      "name": "sam-eventbridge-enricher:EnricherFunction",
      "invokeTarget": {
        "target": "code",
        "projectRoot": "./",
        "lambdaHandler": "functions/enricher.handler"
      },
      "lambda": {
        "runtime": "nodejs12.x",
        "payload": {},
        "environmentVariables": {}
      }
    },
```

The issue persist using target "template" but it's already an improvement over running sam cli with "--debug-port" parameter and using a node attach debug configuration (that works too) :smile:

**Comment by bryceitoc9** [comment] 2020-11-16 23:53
Just a heads-up, the `code` target type means that the toolkit runs your Lambda handler in isolation from the rest of the template file, so this won't work if you're including parameters, Lambda layers, etc. in your `template.yaml` file. If you're not using any such values in the template, this should work identically to what the `template` target type would provide.

**Comment by daaru00** [comment] 2020-12-19 09:51
@bryceitoc9 you totally right.. I found out just now using Layers and I can't get it to work any more. Just switch back using an "attach" configuration and run `sam local invoke` from CLI, seems like the only way to me at the moment.

Just tried to update the plugin to the latest version and still having this issue, I cannot in any way specify the template path (nor automatically when creating the debug configuration, specifying the absolute path, relative, nothing at all) still have the same problem.

**Comment by justinmk3** [comment] 2021-01-11 19:32
@daaru00 @bigdaddyrus  Can you confirm the issue still exists in Toolkit 1.18 (latest release)?

1. use the vscode `Toggle Developer Tools` command to show the devtools window
2. click "Console" in the devtools window
2. in the devtools console, run this code: `require('fs').existsSync('/foo/template.yaml')` (where `/foo/template.yaml` is the **absolute path** to the template.yaml file that the Toolkit can't find
3. does it return `true` or `false` ?

**Comment by daaru00** [comment] 2021-01-19 14:14
Hi @justinmk3,

just tested with 1.18.0 version (the latest one) and the error still exist. I did the test that you suggested and it returns `true`. 

Also did a test with `lstatSync` and it works:
```js
> require('fs').lstatSync('/my/absolute/path/template.yaml')

Stats {dev: 66305, mode: 33188, nlink: 1, uid: 1000, gid: 1000, …}
```
And a final test with `readFileSync`, it can correct read the entire file content:
```js
> require('fs').readFileSync('/my/absolute/path/template.yaml').toString()

"AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
.....
.....
....."
```

**Comment by bryceitoc9** [comment] 2021-01-20 18:47
Hi @daaru00 

I'm wondering if there is a syntax issue with your YAML file? Templates are only added to the registry if they're deemed syntactically correct in the Cloudformation Load function: https://github.com/aws/aws-toolkit-vscode/blob/master/src/shared/cloudformation/cloudformation.ts#L222 ; we might have some discrepancies from what SAM CLI expects.

Could you try setting your AWS Toolkit logging to "Verbose" or "Debug" (`Aws: Log Level` in the Settings UI), restarting the IDE, and looking at the results in the `AWS Toolkit Logs` output channel? Any syntax errors while loading the template should show there. For instance, adding garbage to my `template.yaml` brought up the following error on load:

```
2021-01-20 10:44:51 [VERBOSE]: CloudFormationTemplateRegistry: item file:///xxxxxx/template.yaml is malformed: YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 40, column 24:
      Resource: asdasd asdf: lasdlkj
```

**Comment by dudutwizer** [comment] 2021-01-24 21:29
I had the same issue, and I solved it by moving the handler definition from the global to the resource level.
instead of
```
Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Handler: app.lambda_handler
```

to 
```
Globals:
  Function:
    Timeout: 30
Resources:
  test:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test/
      Events:
        test:
          Type: Api
          Properties:
            Path: /
            Method: post
      Runtime: python3.8
      Handler: app.lambda_handler
```

**Comment by justinmk3** [comment] 2021-01-25 12:59
@dudutwizer thanks for noting that. That particular issue is tracked in https://github.com/aws/aws-toolkit-vscode/issues/1211

For this issue, it looks like we need to message the user when a template.yaml is invalid. Alternatively we could add invalid template.yaml's to the registry, and then surface the validation errors at appropriate times (e.g. when used in a launch config).

**Comment by daaru00** [comment] 2021-01-25 14:29
ah-ah! experienced something similar to @dudutwizer:
```
2021-01-25 15:09:30 [ERROR]: SAM debug: invalid config: Runtime for Template Resource <my function name> in Template file <my absolute template path> is either undefined or unsupported.
```
here what I set in my template file:
```yaml
Globals:
  Function:
    Timeout: 6
    Runtime: nodejs12.x
```

I'm sorry, I hadn't noticed the error message before activating the verbose module logs and searching for them. I use the global field a lot, almost all common configurations and, for the runtime, I use it by default on new templates.. that's the reason why I had this error for basically all my projects :smile:.

Just moved `Runtime` configuration from global to function's properties and the error is gone, thank you everyone!

---

definitely a duplicate of #1211

**Comment by justinmk3** [comment] 2021-01-26 18:36
We should surface this somehow, will keep this open to track that.

**Comment by dudutwizer** [comment] 2021-02-03 17:23
@bryceitoc9 after installing the VSIX file I can confirm it resolves the bug, thanks!

**Comment by justinmk3** [comment] 2021-02-04 19:16
Fixed in Toolkit 1.20

**Closed by justinmk3** 2021-02-04 19:16 UTC
Labels: bug, pending-release, sam, ux

**Comment by josephjoice** [comment] 2021-02-08 03:56
@bryceitoc9 I am on aws toolkit version `v1.20.0`. Still seeing this issue. I have enabled logging and I see 

`CloudFormationTemplateRegistry: manager detected a change to tracked file: /Users/jjoice/content-management/subscriber-lambda-es/template.yaml` 

But on trying to invoke i still see 

`2021-02-08 09:13:25 [ERROR]: SAM debug: invalid config: Invalid (or missing) template file (path must be workspace-relative, or absolute): /Users/jjoice/content-management/subscriber-lambda-es/template.yaml`

```
aws cloudformation validate-template --template-body file://template.yaml
```
returns no error as well.

**Comment by bryceitoc9** [comment] 2021-02-08 16:10
Just making sure, what's your VS Code root folder? `/Users/jj/prod`? Also, how did you create the launch config: by hand or by codelens?

**Comment by josephjoice** [comment] 2021-02-12 17:29
Yes my `.vscode` is in `/Users/jj/proj/`. I created the launch config by hand. I am not getting any `codelens` options on going to my the `template.yaml`. By the way `sam build && sam local invoke -d 5890 IndexingLambda` works without issues.

**Comment by daskabe** [comment] 2022-06-22 19:18
having same issue.

launch.json
```
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "productService:FunctionName",
            "invokeTarget": {
                "target": "template",
                "templatePath": "${workspaceFolder}/template.yml",
                "logicalId": "FunctionName"
            },
            "lambda": {
                "payload": {},
                "environmentVariables": {}
            }
        }
    ]
}
```
//Tool kit log file.
aws_toolkit_20220620T142045.log
```
2022-06-20 14:20:45 [ERROR]: log level: info
2022-06-20 14:20:46 [INFO]: Retrieving AWS endpoint data
2022-06-20 14:20:46 [INFO]: OS: Darwin x64 21.5.0
2022-06-20 14:20:46 [INFO]: Visual Studio Code extension host:  1.68.1
2022-06-20 14:20:46 [INFO]: AWS Toolkit:  1.39.0
2022-06-20 14:20:46 [INFO]: node: 16.13.0
2022-06-20 14:20:46 [INFO]: electron: 17.4.7
2022-06-20 14:25:47 [INFO]: telemetry: sent batch (size=6)
2022-06-21 09:55:48 [INFO]: telemetry: sent batch (size=1)
2022-06-21 10:10:48 [INFO]: telemetry: sent batch (size=1)
2022-06-21 10:35:49 [INFO]: telemetry: sent batch (size=1)
2022-06-21 11:40:49 [INFO]: telemetry: sent batch (size=1)
2022-06-22 13:38:10 [INFO]: telemetry: sent batch (size=1)
2022-06-22 13:40:12 [ERROR]: SAM debug: invalid config: Runtime for Template Resource FunctionName in Template file /Users/daskabe/Documents/workspace/productService/template.yml is either undefined or unsupported.
2022-06-22 13:41:08 [ERROR]: SAM debug: invalid config: Runtime for Template Resource FunctionName in Template file /Users/daskabe/Documents/workspace/productService/template.yml is either undefined or unsupported.
2022-06-22 13:41:52 [ERROR]: SAM debug: invalid config: Runtime for Template Resource FunctionName in Template file /Users/daskabe/Documents/workspace/productService/template.yml is either undefined or unsupported.
2022-06-22 13:43:06 [ERROR]: SAM debug: invalid config: Runtime for Template Resource FunctionName in Template file /Users/daskabe/Documents/workspace/productService/template.yml is either undefined or unsupported.
2022-06-22 13:43:10 [INFO]: telemetry: sent batch (size=1)
2022-06-22 13:45:53 [ERROR]: SAM debug: invalid config: Runtime for Template Resource FunctionName in Template file /Users/daskabe/Documents/workspace/productService/template.yml is either undefined or unsupported.
2022-06-22 13:48:11 [INFO]: telemetry: sent batch (size=1)
2022-06-22 13:58:11 [INFO]: telemetry: sent batch (size=1)

```

**Comment by thefat32** [comment] 2022-08-28 02:05
I'm having this same issue with template generated by CDK. The only log about the file is:

`2022-08-27 22:53:28 [DEBUG]: schema service: handle yaml mapping: [removed] -> C:/Projects/tenlek/tenlek-reports/template.yaml`

Any idea on how to debug this problem?

**Comment by thefat32** [comment] 2022-08-29 17:51
> > Any idea on how to debug this problem?
> 
> If the template.yaml file _contents_ don't look like a SAM file, Toolkit will skip it. What do the contents look like? Also, is the file part of the vscode workspace?

The file el is generated by CDK and I can use it just fine via command line `sam local invoke ...`. But AWS Toolkit does not load it preventing me to use sam cli Debug Configuration. We are starting the sam local invoke debugger with a VS Code preLaunchTask and attaching to the debugger to workaround this problem but it would be nice for AWS Toolkit to support the same templates sam cli does
