### ISSUE TITLE
command aws.codeWhisperer.rejectCodeSuggestion not found

### ISSUE THREAD

**Issue by dgokcin** [aws/aws-toolkit-vscode#4409] opened 2024-02-08 12:04 UTC
## Problem

When using the GitHub Copilot extension, the default keymap for rejecting code suggestions triggers an annoying pop-up suggesting "command aws.codeWhisperer.rejectCodeSuggestion not found." Even though Code Whisperer suggestions are paused, pressing "esc" still results in this popup.

## Steps to reproduce the issue

1. Enable GitHub Copilot extension.

2. Pause Code Whisperer suggestions.

3. Attempt to reject a code suggestion using the default keymap<esc>.

4. Observe the appearance of the pop-up message.

![2024-02-08 12 49 19](https://github.com/aws/aws-toolkit-vscode/assets/33603535/1637a792-5e80-4e6c-a864-622d0e46a0f6)

## Expected behavior

Rejecting code suggestions should not trigger any pop-up messages when Code Whisperer suggestions are paused.

## Additional Information

This issue is disruptive to workflow and interrupts coding sessions. I am creating this new issue because of the related issues marked as closed.

- #3509 (closed)
- #3490 (closed)

## System details (run the `AWS: About Toolkit` command)

- OS: Darwin arm64 23.2.0
- Visual Studio Code extension host:  1.87.0-insider
- AWS Toolkit:  2.8.0
- node: 18.17.1
- electron: 27.2.3

**Comment by Will-ShaoHua** [comment] 2024-02-08 22:17
hey @dgokcin thanks for reporting to us. 
Yes I think you can just sign out from CW and you should be still good to use AWS Toolkit. 
![Screenshot 2024-02-08 at 2 11 59 PM](https://github.com/aws/aws-toolkit-vscode/assets/96078566/cf56f4eb-dcb2-437d-9e3f-43194ca67dcb)

I think the issue results from different inline completion extension interference (Copilot and CodeWhisperer), could you help me verify this aspect by disable Copilot and see if the issue persists? Thanks!

**Comment by dgokcin** [comment] 2024-02-09 08:50
@Will-ShaoHua hello and thanks for the quick reply.

I can confirm that this issue persists only when two inline completion extensions are enabled at the same time. Disabling Copilot made the popup disappear. Ideally, when auto suggestions are paused, I expect the ignoring code suggestions keymap to be disabled as well.

The sign-out approach is not going to work for me because signing out from CW causes a sign-out from Amazon Q as well, and I often toggle between Copilot Chat and Amazon Q during my daily workflow. As a workaround, I found that disabling the keybinding works better for me by adding the following override to my keybindings.json:

```json
  {
    "key": "escape",
    "command": "-aws.codeWhisperer.rejectCodeSuggestion",
    "when": "aws.codewhisperer.connected && inlineSuggestionVisible && !editorReadonly || isCloud9 && suggestWidgetVisible && !editorReadonly"
  }
```

**Comment by Will-ShaoHua** [comment] 2024-02-09 17:57
> Ideally, when auto suggestions are paused, I expect the ignoring code suggestions keymap to be disabled as well.

Understood, we keep the keep binding because users can still trigger CW manually with [option] + [c]. But yes, we will figure out a way to mitigate this issue, after all not all users are aware of having multi inline completion providers is the root cause. 

> As a workaround, I found that disabling the keybinding works better for me by adding the following override to my keybindings.json

yea that works too!

**Comment by terris-peer** [comment] 2024-02-24 16:17
This is particularly annoying when using Vim since it breaks the Escape key which is interpreted by VSCode as rejecting code suggestions.

**Comment by zixlin7** [comment] 2024-06-05 21:02
closing as duplicate of https://github.com/aws/aws-toolkit-vscode/issues/3509

**Closed by zixlin7** 2024-06-05 21:02 UTC
Labels: bug, codewhisperer
