### ISSUE TITLE
An error occurred while loading view: aws.AmazonQChatView

### ISSUE THREAD

**Issue by sangjiexun** [aws/aws-toolkit-vscode#5874] opened 2024-10-28 04:59 UTC
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by justinmk3** [comment] 2024-10-28 17:07
Since there are no details given, I assume this is a duplicate of https://github.com/aws/aws-toolkit-vscode/issues/4503

**Closed as completed by justinmk3** 2024-10-28 17:07 UTC
Labels: bug, amazon-q, startup
