### ISSUE TITLE
"Extension host terminated unexpectedly 3 times within the last 5 minutes." 

### ISSUE THREAD

**Issue by breanne-warner** [aws/aws-toolkit-vscode#5151] opened 2024-06-13 00:03 UTC
Type: <b>Bug</b>

I used the Bisect to identify this extension as the issue

Extension version: 3.9.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650U with Radeon Graphics      (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.31GB (2.67GB free)|
|Process Argv|--crash-reporter-id 3c1cede6-1e82-4c37-8ec1-2e3486e57dd1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by justinmk3** [comment] 2024-06-13 00:05
Can you provide the AWS Toolkit logs? 

1. In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run `AWS: View Logs`. This reveals the Output panel with `AWS Toolkit Logs` selected.
2. Click the gear icon and choose `Debug`, then click it again and choose `Set As Default`.
3. Perform the steps to reproduce the issue.
4. Remove any private info from the logs.

**Comment by up-town-down** [comment] 2024-06-20 13:14
I'm seeing the same error withe the state machine language server, but it's on 3.10.0 and is not occurring in 3.9.0
![Screenshot 2024-06-20 at 14 11 28](https://github.com/aws/aws-toolkit-vscode/assets/11238286/f60aa997-4e82-4644-97d6-e4fc666332ce)
log attached
[toolkit.log](https://github.com/user-attachments/files/15914430/toolkit.log)

**Comment by justinmk3** [comment] 2024-06-20 14:11
@up-town-down in your case does vscode say "extension host" specifically? If not, that is likely a separate issue.

````
Node.js v20.9.0
[Info  - 14:08:16] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/user/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-3.10.0/dist/src/stepFunctions/asl/aslServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at /Users/user/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-3.10.0/dist/src/stepFunctions/asl/aslServer.js:1393:72630
    at /Users/user/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-3.10.0/dist/src/stepFunctions/asl/aslServer.js:1394:7362
    at Object.<anonymous> (/Users/user/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-3.10.0/dist/src/stepFunctions/asl/aslServer.js:1394:7401)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-3.10.0/dist/src/stepFunctions/asl/aslServer.js'
  ]
}
```

**Comment by up-town-down** [comment] 2024-06-20 14:23
Possibly is separate then - I honed in on the rest of the error message - my bad :)

**Comment by justinmk3** [comment] 2024-06-20 19:32
After updating to the latest version, are you still seeing this problem?

Possibly fixed by: 

- https://github.com/aws/aws-toolkit-vscode/pull/5129
- https://github.com/aws/aws-toolkit-vscode/pull/5183

**Comment by justinmk3** [comment] 2024-06-22 11:21
Please update the extension(s) to the latest version, and restart vscode. Let us know if the issue is not resolved!

**Closed by justinmk3** 2024-06-22 11:21 UTC
Labels: needs-response, pending-release, performance
