### ISSUE TITLE
VSC automatically switching to Output window on launch with AWS SAM CLI

### ISSUE THREAD

**Issue by capegreg** [aws/aws-toolkit-vscode#1578] opened 2021-03-18 12:54 UTC
-   OS: Windows
-   VS Code version: 1.54.3
-   AWS Toolkit extension version: v1.21.0

When launching VSC the Output window automatically opens to the AWS Toolkit task and prompts that AWS Toolkit now requires that SAM CLI is installed. The issue goes away if I disable AWS Toolkit, but I need that; not SAM CLI.

![Screenshot 2021-03-18 084814](https://user-images.githubusercontent.com/1051118/111628550-b7b07000-87c6-11eb-9395-7a4abadc14eb.png)

**Comment by justinmk3** [comment] 2021-03-18 20:24
Thank you for the report! May be the same root cause as https://github.com/aws/aws-toolkit-vscode/issues/1580 , we are investigating.

**Comment by justinmk3** [comment] 2021-03-18 21:13
Confirmed that https://github.com/aws/aws-toolkit-vscode/pull/1582 fixes this.

**Comment by justinmk3** [comment] 2021-03-19 21:24
Toolkit 1.22 released with a fix for this.

**Closed by justinmk3** 2021-03-19 21:24 UTC
Labels: bug, guidance, pending-release, sam
