### ISSUE TITLE
settings.json: $ref '/definitions/jsonObject' in 'vscode://schemas/launch' can not be resolved

### ISSUE THREAD

**Issue by ryenus** [aws/aws-toolkit-vscode#1027] opened 2020-04-14 13:54 UTC
**Describe the bug**

In VSCode, with AWS Toolkit **1.8.0** installed, there's an warning in `settings.json` at the first opening curly brace:

`$ref '/definitions/jsonObject' in 'vscode://schemas/launch' can not be resolved.`

**To Reproduce**

1. Install AWS Toolkit, namely the latest version **1.8.0**, in VSCode.
2. open VSCode `settings.json`
3. the mentioned error appears in the Problems view.

**Expected behavior**
There should be no such error.

**Screenshots**
![image](https://user-images.githubusercontent.com/610161/79039652-5cb8e500-7c15-11ea-823b-5db14c22da5e.png)

**Desktop (please complete the following information):**

-   OS: macOS 10.15.4
-   Visual Studio Code Version: 1.44
-   AWS Toolkit Version: 1.8.0

**Additional context**
There's no such error with AWS Toolkit `1.7.0`
See also: https://github.com/microsoft/vscode/issues/95033

**Comment by dsyorkd** [comment] 2020-04-14 15:13
Also seeing this behavior, disabling the plugin or downgrading resolves this issue for me. 

- OS: macOS 10.15.3
- Visual Studio Code Version: 1.44
- AWS Toolkit Version 1.8.0

**Comment by bryceitoc9** [comment] 2020-04-14 15:29
I'll take a look. Just making sure, this occurs with the extension both activated and un-activated (read: extension is installed but has not been clicked during the IDE session)?

**Comment by dsyorkd** [comment] 2020-04-14 15:31
Yes, for me it was doing this unactivated. I didn't try it activated.

**Comment by gandroz** [comment] 2020-04-14 16:10
same here but with the launch.json file

**Comment by bryceitoc9** [comment] 2020-04-14 16:10
Looks like this only appears on activation (if you're booting the IDE with the file explorer open, you may be automatically activating the extension due to the CDK panel) and is caused by this definition in our package.json: https://github.com/aws/aws-toolkit-vscode/blob/master/package.json#L152 ; not sure why it's affecting files that aren't the VS Code launch.json though. 

We'll keep investigating; thanks for the heads-up!

**Comment by bryceitoc9** [comment] 2020-04-14 20:53
Fix here: https://github.com/aws/aws-toolkit-vscode/pull/1029 , will reach out to VS Code for clarification on the expected contents of the package.json (we're still using some JSON Schemas-specific flags, e.g. `$schema`; don't want that to potentially be an issue later).

**Comment by bryceitoc9** [comment] 2020-04-14 21:22
Opened an issue with VS Code: https://github.com/microsoft/vscode/issues/95270

**Comment by awschristou** [comment] 2020-04-29 19:08
This issue has been resolved with v1.9.0 of the toolkit, which is now available.

**Closed by awschristou** 2020-04-29 19:08 UTC
Labels: bug
