### ISSUE TITLE
Is it possible to use {proxy+} in my route for template-based API Gateway debugging?

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-vscode#2446] opened 2022-01-20 17:26 UTC
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.63.2
-   AWS Toolkit extension version: 1.35.0

**Question**

I have an SAM template setup such that my API Gateway has a single route that consists only of `/{proxy+}` and with it I'm using Express JS.  In the [documentation](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/debug-apigateway.html), it states that the `api.path` value...

> Must be a valid API path resolved from the `template.yaml` specified by `invokeTarget.templatePath`.

I tried setting up `api.path` in the `launch.json` configuration with both a valid route and with `/{proxy+}` (which I knew wouldn't work, but hey), but I get the follow error in either case:

> [ERROR]: Local API failed to respond (ECONNREFUSED) after 30 retries, path: /{proxy+}, error: connect ECONNREFUSED 127.0.0.1:5860

Is it possible to use AWS Toolkit debugging with this setup?

Thanks.

**Comment by JadenSimon** [comment] 2022-01-21 21:10
Hey @ryancabanas ,

Using `/{proxy+}` in a HelloWorldFunction template appears to work correctly for me. In my template I have
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /foo/{proxy+}
            Method: get
```
And my `launch.json`:
```json
{
  "type": "aws-sam",
  "request": "direct-invoke",
  "name": "API lambda-nodejs14.x:HelloWorldFunction (nodejs14.x)",
  "invokeTarget": {
      "target": "api",
      "templatePath": "${workspaceFolder}/lambda-nodejs14.x/template.yaml",
      "logicalId": "HelloWorldFunction"
  },
  "api": {
      "path": "/foo/bar",
      "httpMethod": "get",
  },
  "lambda": {
      "runtime": "nodejs14.x"
  }
}
```

Succeeds with:
```
Debugger attached.
END RequestId: bc52d932-fb28-4578-8c6f-893832d18890
REPORT RequestId: bc52d932-fb28-4578-8c6f-893832d18890	Init Duration: 0.65 ms	Duration: 2601.88 ms	Billed Duration: 2602 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2022-01-21 12:54:35,402 | Cleaning all decompressed code dirs
2022-01-21 12:54:35,403 | No Content-Type given. Defaulting to 'application/json'.
2022-01-21 12:54:35 127.0.0.1 - - [21/Jan/2022 12:54:35] "GET /foo/bar HTTP/1.1" 200 -
```

The specific error you mention is pretty much a generic failure for the local server either not starting or being too slow to respond. So there's many potential reasons for why this isn't working for your case. I'd need some additional details or your log output (use the `AWS: View Toolkit Logs` command). May also want to set your logging level to 'debug' via the VS Code setting `aws.logLevel`

**Comment by ryancabanas** [comment] 2022-01-26 22:17
Hi @JadenSimon,

Sorry for the late reply.

Let me double-check my settings against the example you provided and see if I'm missing anything.  I will also try the debug settings you mention and see if I can redact and share log info.

One thing I forgot to mention is that in my application I am using a Lambda Layer to house all of the npm packages I'm using.  I don't know if that would cause problems in this scenario, as well.

Thanks!

**Comment by ryancabanas** [comment] 2022-01-27 17:45
Hi @JadenSimon,

Okay.  I still couldn't get it to work.  I went ahead and set up a vanilla hello world SAM application using `sam init` and tried running the api debugger and still ran into the same issue.  I found this post (https://stackoverflow.com/questions/67607436/vscode-launch-json-failed-to-start-local-api-gateway-timeout-while-waiting-for) where someone talks about the same exact problem I'm having and they say they solved the issue, but the settings they say to change don't exist in Visual Studio Code for me.  :(

So I went ahead and set the `Aws: Log Level` to `debug` in Visual Studio Code and here is the AWS Toolkit Log generated when attempting to use the api debugging with the simple hello world app.

Thank you for the help!

```2022-01-27 12:13:03 [INFO]: Setting log level to: debug
2022-01-27 12:13:03 [DEBUG]: Log level is now: debug
2022-01-27 12:13:03 [DEBUG]: Log level is now: debug
2022-01-27 12:13:16 [VERBOSE]: SAM debug: config: "Test"
2022-01-27 12:13:17 [INFO]: Preparing to debug locally: API "/hello", Lambda "app.lambdaHandler"
2022-01-27 12:13:17 [INFO]: Building SAM application...
2022-01-27 12:13:17 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --debug --build-dir C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output --template C:/Users/Ryan/Desktop/projects/tests/sam-app/template.yaml]
2022-01-27 12:13:17 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --debug --build-dir C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output --template C:/Users/Ryan/Desktop/projects/tests/sam-app/template.yaml]
2022-01-27 12:13:17 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --debug --build-dir C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output --template C:/Users/Ryan/Desktop/projects/tests/sam-app/template.yaml]
2022-01-27 12:13:21 [VERBOSE]: stderr: 2022-01-27 12:13:21,440 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

2022-01-27 12:13:21 [VERBOSE]: stderr: 2022-01-27 12:13:21,440 | Using config file: samconfig.toml, config environment: default
2022-01-27 12:13:21,440 | Expand command line arguments to:
2022-01-27 12:13:21,440 | --template_file=C:\Users\Ryan\Desktop\projects\tests\sam-app\template.yaml --build_dir=C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output --cache_dir=.aws-sam\cache 

2022-01-27 12:13:23 [VERBOSE]: stderr: 2022-01-27 12:13:23,940 | 'build' command is called

2022-01-27 12:13:23 [VERBOSE]: stderr: 2022-01-27 12:13:23,958 | No Parameters detected in the template

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,043 | 2 stacks found in the template

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,043 | No Parameters detected in the template

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,089 | 2 resources found in the stack 

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,089 | No Parameters detected in the template

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,139 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,140 | --base-dir is not presented, adjusting uri hello-world/ relative to C:\Users\Ryan\Desktop\projects\tests\sam-app\template.yaml
2022-01-27 12:13:24,141 | No Parameters detected in the template

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,189 | Instantiating build definitions

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,189 | No previous build graph found, generating new one
2022-01-27 12:13:24,189 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(nodejs14.x, C:\Users\Ryan\Desktop\projects\tests\sam-app\hello-world, Zip, , 4d0b941a-dbf6-4809-a54f-e071cb5e28f9, {}, {}, x86_64, []), Function: Function(name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='nodejs14.x', memory=None, timeout=3, handler='app.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Users\\Ryan\\Desktop\\projects\\tests\\sam-app\\hello-world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], stack_path=''))

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,198 | Building codeuri: C:\Users\Ryan\Desktop\projects\tests\sam-app\hello-world runtime: nodejs14.x metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,198 | Building to following folder C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\HelloWorldFunction

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,204 | Loading workflow module 'aws_lambda_builders.workflows'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,267 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,293 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,320 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,343 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,372 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,418 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,450 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,482 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,517 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,517 | Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,702 | Running workflow 'NodejsNpmBuilder'

2022-01-27 12:13:24 [VERBOSE]: stderr: 2022-01-27 12:13:24,702 | Running NodejsNpmBuilder:NpmPack
2022-01-27 12:13:24,702 | NODEJS packaging file:C:\Users\Ryan\Desktop\projects\tests\sam-app\hello-world to C:\Users\Ryan\AppData\Local\Temp\tmpy8gg2j5k
2022-01-27 12:13:24,702 | executing NPM: ['npm.cmd', 'pack', '-q', 'file:C:\\Users\\Ryan\\Desktop\\projects\\tests\\sam-app\\hello-world']

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,055 | NODEJS packed to hello_world-1.0.0.tgz

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,055 | NODEJS extracting to C:\Users\Ryan\AppData\Local\Temp\tmpy8gg2j5k\unpacked

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,086 | NodejsNpmBuilder:NpmPack succeeded

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,086 | Running NodejsNpmBuilder:CopyNpmrc
2022-01-27 12:13:29,086 | NodejsNpmBuilder:CopyNpmrc succeeded
2022-01-27 12:13:29,086 | Running NodejsNpmBuilder:CopySource

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,109 | NodejsNpmBuilder:CopySource succeeded

2022-01-27 12:13:29 [VERBOSE]: stderr: 2022-01-27 12:13:29,109 | Running NodejsNpmBuilder:NpmInstall
2022-01-27 12:13:29,113 | NODEJS installing in: C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\HelloWorldFunction
2022-01-27 12:13:29,113 | executing NPM: ['npm.cmd', 'install', '-q', '--no-audit', '--no-save', '--production', '--unsafe-perm']

2022-01-27 12:13:44 [VERBOSE]: stderr: 2022-01-27 12:13:44,198 | NodejsNpmBuilder:NpmInstall succeeded

2022-01-27 12:13:44 [VERBOSE]: stderr: 2022-01-27 12:13:44,199 | Running NodejsNpmBuilder:CleanUpNpmrc
2022-01-27 12:13:44,199 | NodejsNpmBuilder:CleanUpNpmrc succeeded

2022-01-27 12:13:44 [VERBOSE]: stdout: 
Build Succeeded

2022-01-27 12:13:44 [VERBOSE]: stdout: 
Built Artifacts  : ..\..\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output
Built Template   : ..\..\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke -t ..\..\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml
[*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
[*] Deploy: sam deploy --guided --template-file ..\..\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml
        

2022-01-27 12:13:44 [VERBOSE]: stderr: 2022-01-27 12:13:44,223 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'aa0ee1f3-169f-4574-9b39-b2045577d79b', 'installationId': 'c683734c-1412-460a-8666-9e6e7f0ab412', 'sessionId': '4739eee3-5673-4e9e-9fdd-bd1941501c35', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.36.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 22782, 'exitReason': 'success', 'exitCode': 0}}]}

2022-01-27 12:13:44 [VERBOSE]: stderr: 2022-01-27 12:13:44,746 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

2022-01-27 12:13:44 [INFO]: Build complete.
2022-01-27 12:13:44 [DEBUG]: localLambdaRunner.invokeLambdaFunction: Test
2022-01-27 12:13:44 [INFO]: Starting SAM application locally
2022-01-27 12:13:44 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd local start-api --debug --template C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml --port 5869 --debug-port 5870]
2022-01-27 12:13:44 [INFO]: AWS.running.command
2022-01-27 12:13:44 [INFO]: Sending request to local API: http://127.0.0.1:5869/hello?
2022-01-27 12:13:44 [DEBUG]: Local API: retry (1 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:45 [DEBUG]: Local API: retry (2 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:45 [DEBUG]: Local API: retry (3 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:45 [DEBUG]: Local API: retry (4 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:45 [DEBUG]: Local API: retry (5 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:46 [DEBUG]: Local API: retry (6 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:46 [DEBUG]: Local API: retry (7 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:46 [DEBUG]: Local API: retry (8 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:46 [DEBUG]: Local API: retry (9 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:46 [DEBUG]: Local API: retry (10 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:47 [DEBUG]: Local API: retry (11 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:47 [DEBUG]: Local API: retry (12 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:47 [DEBUG]: Local API: retry (13 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:47 [DEBUG]: Local API: retry (14 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:48 [DEBUG]: Local API: retry (15 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:48 [DEBUG]: Local API: retry (16 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:48 [DEBUG]: Local API: retry (17 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:48 [DEBUG]: Local API: retry (18 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:48 [DEBUG]: Local API: retry (19 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:49 [DEBUG]: Local API: retry (20 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:49 [DEBUG]: Local API: retry (21 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:49 [DEBUG]: Local API: retry (22 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:49 [DEBUG]: Local API: retry (23 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:49 [DEBUG]: Local API: retry (24 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:50 [DEBUG]: Local API: retry (25 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:50 [DEBUG]: Local API: retry (26 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:50 [DEBUG]: Local API: retry (27 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:50 [DEBUG]: Local API: retry (28 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:51 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:51,020 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

2022-01-27 12:13:51 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:51,020 | Using config file: samconfig.toml, config environment: default
2022-01-27 12:13:51,020 | Expand command line arguments to:
2022-01-27 12:13:51,020 | --template_file=C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml --port=5869 --debug_port=(5870,) --host=127.0.0.1 --static_dir=public --layer_cache_basedir=C:\Users\Ryan\AppData\Roaming\AWS SAM\layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 

2022-01-27 12:13:51 [DEBUG]: Local API: retry (29 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:51 [DEBUG]: Local API: retry (30 of 30): http://127.0.0.1:5869/hello?: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:51 [ERROR]: Local API failed to respond (ECONNREFUSED) after 30 retries, path: /hello, error: connect ECONNREFUSED 127.0.0.1:5869
2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,414 | local start-api command is called

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,430 | No Parameters detected in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,513 | 2 stacks found in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,513 | No Parameters detected in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,550 | 2 resources found in the stack 

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,550 | No Parameters detected in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,590 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,591 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\Users\Ryan\AppData\Local\Temp\aws-toolkit-vscode\vsctkdp6IIJ\output\template.yaml

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,615 | No Parameters detected in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,651 | No Parameters detected in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,690 | Found '1' API Events in Serverless function with name 'HelloWorldFunction'

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,690 | Detected Inline Swagger definition
2022-01-27 12:13:53,690 | Lambda function integration not found in Swagger document at path='/hello' method='get'
2022-01-27 12:13:53,690 | Found '0' APIs in resource 'ServerlessRestApi'
2022-01-27 12:13:53,690 | Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
2022-01-27 12:13:53,690 | 1 APIs found in the template

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,707 | Mounting HelloWorldFunction at http://127.0.0.1:5869/hello [GET]

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53,707 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2022-01-27 12:13:53,707 | Localhost server is starting up. Multi-threading = False

2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53  * Running on http://127.0.0.1:5869/ (Press CTRL+C to quit)

2022-01-27 12:14:49 [DEBUG]: telemetry: emitted metric "vscode_viewLogs"
2022-01-27 12:15:48 [INFO]: telemetry: sent batch (size=2)
2022-01-27 12:18:03 [ERROR]: Error running command "sam local start-api": Timeout token expired
2022-01-27 12:18:03 [DEBUG]: telemetry: emitted metric "apigateway_invokeLocal"
2022-01-27 12:18:03 [ERROR]: Failed to start local API Gateway: Timeout token expired
2022-01-27 12:18:03 [WARN]: Ag [Error]: Timeout token expired
    at Timeout._onTimeout (c:\Users\Ryan\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.35.0\dist\extension.js:1342:529)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  type: 'expired'
}
2022-01-27 12:20:48 [INFO]: telemetry: sent batch (size=1)
```

**Comment by ryancabanas** [comment] 2022-01-27 17:49
@JadenSimon,

Sorry.  I forgot to provide the `launch.json` configuration, which I created using the `AWS: SAM Debug Configuration Editor` in VSCode, which is pretty neat.  Didn't know that existed.  Anyway, here's my configuration.

```
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "invokeTarget": {
                "target": "api",
                "logicalId": "HelloWorldFunction",
                "templatePath": "C:\\Users\\Ryan\\Desktop\\projects\\tests\\sam-app\\template.yaml"
            },
            "lambda": {
                "runtime": "nodejs14.x"
            },
            "sam": {
                "containerBuild": false,
                "skipNewImageCheck": false
            },
            "api": {
                "path": "/hello",
                "httpMethod": "get"
            },
            "name": "Test"
        }
    ]
}

**Comment by JadenSimon** [comment] 2022-01-28 01:34
@ryancabanas 

Looking at your logs, it looks like SAM CLI is taking a long time to start (5+ seconds). The toolkit currently tries polling SAM CLI as soon as the process begins executing. There's no way to configure how long the toolkit will poll for, so the only thing I can think of right now is to see if there's anyway to get SAM CLI to start faster? I couldn't find any issues regarding start-up time over at SAM CLI's repository so it's probably machine-dependent. For example, my mac can start it in half a second, but my windows machine easily takes 3 or 4.

I'll need to dig around more for why SAM CLI takes so long on certain machines. The toolkit should also find a better way to know when SAM CLI has started the server, perhaps by listening for some sort of output.

**Comment by ryancabanas** [comment] 2022-01-28 14:46
Hi @JadenSimon,

Thanks so much for looking into this for me!

Based on that person's post on StackOverflow (https://stackoverflow.com/questions/67607436/vscode-launch-json-failed-to-start-local-api-gateway-timeout-while-waiting-for), do you think that I'm not seeing the same setting as they are because I'm using a later version of the AWS Toolkit?  Would downgrading the Toolkit give me such a setting that was mentioned, which might allow me to adjust the timeout setting?

Thanks.

**Comment by JadenSimon** [comment] 2022-01-28 17:58
@ryancabanas 

You're correct that the setting no longer exists in the latest toolkit version. There is a similar setting for debugger attachment (Aws > Samcli > Lambda > Timeout) but I don't think this would help here since it's used for the entire debugging workflow. The problem is that we have hard-coded a maximum time of 6 seconds for API gateway attachment :(

This problem is reflected in the logs. SAM CLI does start the local server:
```
2022-01-27 12:13:53 [VERBOSE]: SAM: pid 15168: stderr: 2022-01-27 12:13:53  * Running on http://127.0.0.1:5869/ (Press CTRL+C to quit)
```
But notice that this occurs 9 seconds after polling starts:
```
2022-01-27 12:13:44 [INFO]: Sending request to local API: http://127.0.0.1:5869/hello?
```

The toolkit provides limited support for debugger attachment for API gateway invocations (#1840), and this timeout is just another example of this.

I'll see about getting some sort of solution for this problem (and other hard-coded timeouts) in the next release, but in the interim you could try running SAM CLI directly (i.e. no toolkit). This looks like a decent guide for Node: https://www.moesif.com/blog/technical/serverless/debug-lambda-functions-locally-with-the-sam-cli-and-vscode/. Note the guide uses `sam local invoke` while we want to use `sam local start-api` instead.

It isn't perfect, but it should at least get you on a path towards debugging your application. Please feel free to reach out if you run into any issues (or have more questions) about getting the debugger set-up.

**Comment by ryancabanas** [comment] 2022-01-28 21:16
@JadenSimon

Thanks so much for your help!  I'll look into using `sam local invoke`.

Regarding improving debugger support for `sam local start-api`, yeah, it would be good to have some other, typical `sam local start-api` support, as well, if possible.  For example, I use `-p` for different ports sometimes, I needed to use `--parameter-overrides` today, I often use `-l` for logging, and I've come to appreciate `--warm-containers` too.  Not to make better debugger support more difficult to implement, but just thought I'd mention some of those often-used switches while we're on the topic.  😁 

Thanks so much again!  Have a good weekend!

**Comment by JadenSimon** [comment] 2022-01-28 22:32
>  For example, I use -p for different ports sometimes, I needed to use --parameter-overrides today, I often use -l for logging, and I've come to appreciate --warm-containers too. Not to make better debugger support more difficult to implement, but just thought I'd mention some of those often-used switches while we're on the topic. 😁

That's definitely a pain-point. Right now the toolkits have an 'escape-hatch' in the launch configurations via `localArguments` (or `buildArguments` for building) that forwards arguments to SAM CLI:
```json
  "sam": {
        "localArguments": ["-p", "4040"]
    },
```
But this specific example would break debugging `sam local start-api` as the toolkit expects the ports to be in a certain way. And I'm sure there's plenty of things SAM CLI supports that just wouldn't work nicely with the toolkit. Definitely appreciate the feedback though, very helpful! 

> Thanks so much again! Have a good weekend!

You're welcome! You as well. 
I'm closing out this issue and opening a new one to track API debugging improvements which I'll link back here.

**Closed by JadenSimon** 2022-01-28 22:32 UTC
Labels: guidance, sam, performance
