### ISSUE TITLE
Users are able to build SAM applications inside the docker container. [Epic]

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#463] opened 2019-04-04 20:13 UTC
The `sam build` command has a `--use-container` flag. When this flag is set, the application is built inside the lambda docker container, rather than on the host machine.

**Comment by justinmk3** [comment] 2020-07-30 22:38
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/370

**Closed by justinmk3** 2020-07-30 22:38 UTC
Labels: feature-request
