### ISSUE TITLE
Ability to Copy Lambda ARN in AWS Toolkit for vscode

### ISSUE THREAD

**Issue by moneerrifai** [aws/aws-toolkit-vscode#1004] opened 2020-04-02 19:05 UTC
**Is your feature request related to a problem? Please describe.**

The new support for Step Functions is amazing! Since it is common to use Step Functions to orchestrate Lambda functions, it would be nice to be able to grab the Lambda ARN right from vscode and copy/paste it into the state machine definition. When you hover over a Lambda in vscode, you can see its ARN but you cannot copy it.

**Describe the solution you'd like**
Right click on a Lambda function in vscode inside the AWS Toolkit, and have an option to copy the Lambda ARN

**Describe alternatives you've considered**
Currently, the only way to get the ARN is by going to the console, searching for the Lambda, and copying its ARN

**Additional context**
This came up during a Twitch session with Rob Sutter and Richard Boyd

**Comment by justinmk3** [comment] 2020-04-02 19:51
related https://github.com/aws/aws-toolkit-vscode/issues/783

**Comment by moneerrifai** [comment] 2020-04-03 14:41
@justinmk3 thanks. I noticed the other open issue but I am confused by it because the Lambda context menu does not have the option to copy ARN like that other issue claims:

<img width="358" alt="LambdaContextMenu" src="https://user-images.githubusercontent.com/5445607/78372755-49f83d80-758f-11ea-9c7e-182ee1815dc1.png">

**Comment by awschristou** [comment] 2020-04-03 15:31
It should be reasonable to consider this issue a duplicate of #783

**Closed** 2020-04-03 18:48 UTC
Labels: duplicate, feature-request
