### ISSUE TITLE
Sign the VSIX we produce

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-vscode#633] opened 2019-06-21 16:38 UTC
Broken out of issue #166

Digitally signs .vsix file (just like the AWS VSTS toolkit/Visual Studio Toolkit does)

**Comment by justinmk3** [comment] 2020-07-30 23:13
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/209

**Closed by justinmk3** 2020-07-30 23:13 UTC
Labels: technical-debt
